/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.silabos;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Daniel
 */
public class frmBibliografia extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmBibliografia
     */
    public frmBibliografia() {
        initComponents();
    }

    public JCheckBox getCbxAutorCorporativo() {
        return CbxAutorCorporativo;
    }

    public void setCbxAutorCorporativo(JCheckBox CbxAutorCorporativo) {
        this.CbxAutorCorporativo = CbxAutorCorporativo;
    }

    public JButton getGuardarB() {
        return GuardarB;
    }

    public void setGuardarB(JButton GuardarB) {
        this.GuardarB = GuardarB;
    }

    public JButton getBtnCancelarB() {
        return btnCancelarB;
    }

    public void setBtnCancelarB(JButton btnCancelarB) {
        this.btnCancelarB = btnCancelarB;
    }

    public JLabel getLbAnio() {
        return lbAnio;
    }

    public void setLbAnio(JLabel lbAnio) {
        this.lbAnio = lbAnio;
    }

    public JLabel getLbAutor() {
        return lbAutor;
    }

    public void setLbAutor(JLabel lbAutor) {
        this.lbAutor = lbAutor;
    }

    public JLabel getLbCiudad() {
        return lbCiudad;
    }

    public void setLbCiudad(JLabel lbCiudad) {
        this.lbCiudad = lbCiudad;
    }

    public JLabel getLbEditor() {
        return lbEditor;
    }

    public void setLbEditor(JLabel lbEditor) {
        this.lbEditor = lbEditor;
    }

    public JLabel getLbTitulo() {
        return lbTitulo;
    }

    public void setLbTitulo(JLabel lbTitulo) {
        this.lbTitulo = lbTitulo;
    }

    public JLabel getLbTituloVentanaCBApa() {
        return lbTituloVentanaCBApa;
    }

    public void setLbTituloVentanaCBApa(JLabel lbTituloVentanaCBApa) {
        this.lbTituloVentanaCBApa = lbTituloVentanaCBApa;
    }

    public JTextField getTxtAnio() {
        return txtAnio;
    }

    public void setTxtAnio(JTextField txtAnio) {
        this.txtAnio = txtAnio;
    }

    public JTextField getTxtAutor() {
        return txtAutor;
    }

    public void setTxtAutor(JTextField txtAutor) {
        this.txtAutor = txtAutor;
    }

    public JTextField getTxtAutorCorporativo() {
        return txtAutorCorporativo;
    }

    public void setTxtAutorCorporativo(JTextField txtAutorCorporativo) {
        this.txtAutorCorporativo = txtAutorCorporativo;
    }

    public JTextField getTxtCiudad() {
        return txtCiudad;
    }

    public void setTxtCiudad(JTextField txtCiudad) {
        this.txtCiudad = txtCiudad;
    }

    public JTextField getTxtEditor() {
        return txtEditor;
    }

    public void setTxtEditor(JTextField txtEditor) {
        this.txtEditor = txtEditor;
    }

    public JTextField getTxtTitulo() {
        return txtTitulo;
    }

    public void setTxtTitulo(JTextField txtTitulo) {
        this.txtTitulo = txtTitulo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTituloVentanaCBApa = new javax.swing.JLabel();
        lbAutor = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        txtAutorCorporativo = new javax.swing.JTextField();
        lbTitulo = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        lbAnio = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        lbCiudad = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        lbEditor = new javax.swing.JLabel();
        txtEditor = new javax.swing.JTextField();
        CbxAutorCorporativo = new javax.swing.JCheckBox();
        btnCancelarB = new javax.swing.JButton();
        GuardarB = new javax.swing.JButton();

        lbTituloVentanaCBApa.setText("Campos Bibliograficos de APA");

        lbAutor.setText("Autor");

        lbTitulo.setText("Titulo");

        lbAnio.setText("Año");

        lbCiudad.setText("Ciudad");

        lbEditor.setText("Editor");

        CbxAutorCorporativo.setText("Autor Corporativo");

        btnCancelarB.setText("Cancelar");

        GuardarB.setText("Guardar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTituloVentanaCBApa)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lbEditor))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(CbxAutorCorporativo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtAutorCorporativo, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtEditor, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbAnio)
                                        .addComponent(lbTitulo)
                                        .addComponent(lbCiudad)
                                        .addComponent(lbAutor))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtAnio)
                                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtCiudad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnCancelarB)
                                    .addGap(18, 18, 18)
                                    .addComponent(GuardarB))))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbTituloVentanaCBApa)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAutor)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAutorCorporativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbxAutorCorporativo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAnio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCiudad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbEditor)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txtEditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarB)
                    .addComponent(GuardarB))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CbxAutorCorporativo;
    private javax.swing.JButton GuardarB;
    private javax.swing.JButton btnCancelarB;
    private javax.swing.JLabel lbAnio;
    private javax.swing.JLabel lbAutor;
    private javax.swing.JLabel lbCiudad;
    private javax.swing.JLabel lbEditor;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbTituloVentanaCBApa;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtAutorCorporativo;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtEditor;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
