/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.silabos;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Daniel
 */
public class frmBibliografia extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmBibliografia
     */
    public frmBibliografia() {
        initComponents();
    }

    public JCheckBox getCbxExistenciaBiblioteca() {
        return cbxExistenciaBiblioteca;
    }

    public void setCbxExistenciaBiblioteca(JCheckBox cbxExistenciaBiblioteca) {
        this.cbxExistenciaBiblioteca = cbxExistenciaBiblioteca;
    }

    public JLabel getLbObeservaciones() {
        return lbObeservaciones;
    }

    public void setLbObeservaciones(JLabel lbObeservaciones) {
        this.lbObeservaciones = lbObeservaciones;
    }

    public JTextField getTxtObservaciones() {
        return txtObservaciones;
    }

    public void setTxtObservaciones(JTextField txtObservaciones) {
        this.txtObservaciones = txtObservaciones;
    }

    public JTextField getTxtCodigoLibro() {
        return txtCodigoLibro;
    }

    public JCheckBox getCbxAutorCorporativo() {
        return CbxAutorCorporativo;
    }

    public void setCbxAutorCorporativo(JCheckBox CbxAutorCorporativo) {
        this.CbxAutorCorporativo = CbxAutorCorporativo;
    }

    public JButton getGuardarB() {
        return GuardarB;
    }

    public void setGuardarB(JButton GuardarB) {
        this.GuardarB = GuardarB;
    }

    public JButton getBtnCancelarB() {
        return btnCancelarB;
    }

    public void setBtnCancelarB(JButton btnCancelarB) {
        this.btnCancelarB = btnCancelarB;
    }

    public JLabel getLbAnio() {
        return lbAnio;
    }

    public void setLbAnio(JLabel lbAnio) {
        this.lbAnio = lbAnio;
    }

    public JLabel getLbAutor() {
        return lbAutor;
    }

    public void setLbAutor(JLabel lbAutor) {
        this.lbAutor = lbAutor;
    }

    public JLabel getLbCiudad() {
        return lbCiudad;
    }

    public void setLbCiudad(JLabel lbCiudad) {
        this.lbCiudad = lbCiudad;
    }

    public JLabel getLbEditor() {
        return lbEditor;
    }

    public void setLbEditor(JLabel lbEditor) {
        this.lbEditor = lbEditor;
    }

    public JLabel getLbTitulo() {
        return lbTitulo;
    }

    public void setLbTitulo(JLabel lbTitulo) {
        this.lbTitulo = lbTitulo;
    }

    public JLabel getLbTituloVentanaCBApa() {
        return lbTituloVentanaCBApa;
    }

    public void setLbTituloVentanaCBApa(JLabel lbTituloVentanaCBApa) {
        this.lbTituloVentanaCBApa = lbTituloVentanaCBApa;
    }

    public JTextField getTxtAnio() {
        return txtAnio;
    }

    public void setTxtAnio(JTextField txtAnio) {
        this.txtAnio = txtAnio;
    }

    public JTextField getTxtAutor() {
        return txtAutor;
    }

    public void setTxtAutor(JTextField txtAutor) {
        this.txtAutor = txtAutor;
    }

    public JTextField getTxtAutorCorporativo() {
        return txtAutorCorporativo;
    }

    public void setTxtAutorCorporativo(JTextField txtAutorCorporativo) {
        this.txtAutorCorporativo = txtAutorCorporativo;
    }

    public JTextField getTxtCiudad() {
        return txtCiudad;
    }

    public void setTxtCiudad(JTextField txtCiudad) {
        this.txtCiudad = txtCiudad;
    }

    public JTextField getTxtEditor() {
        return txtEditor;
    }

    public void setTxtEditor(JTextField txtEditor) {
        this.txtEditor = txtEditor;
    }

    public JTextField getTxtTitulo() {
        return txtTitulo;
    }

    public void setTxtTitulo(JTextField txtTitulo) {
        this.txtTitulo = txtTitulo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        lbTituloVentanaCBApa = new javax.swing.JLabel();
        lbAutor = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        txtAutorCorporativo = new javax.swing.JTextField();
        lbTitulo = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        lbAnio = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        lbCiudad = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        lbEditor = new javax.swing.JLabel();
        txtEditor = new javax.swing.JTextField();
        CbxAutorCorporativo = new javax.swing.JCheckBox();
        btnCancelarB = new javax.swing.JButton();
        GuardarB = new javax.swing.JButton();
        lbCodigoLibro = new javax.swing.JLabel();
        txtCodigoLibro = new javax.swing.JTextField();
        txtObservaciones = new javax.swing.JTextField();
        lbObeservaciones = new javax.swing.JLabel();
        cbxExistenciaBiblioteca = new javax.swing.JCheckBox();

        jRadioButton1.setText("jRadioButton1");

        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        lbTituloVentanaCBApa.setText("Campos Bibliograficos de APA");

        lbAutor.setText("Autor");

        txtAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorActionPerformed(evt);
            }
        });

        lbTitulo.setText("Titulo");

        lbAnio.setText("Año");

        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });

        lbCiudad.setText("Ciudad");

        lbEditor.setText("Editor");

        txtEditor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditorActionPerformed(evt);
            }
        });

        CbxAutorCorporativo.setText("Autor Corporativo");

        btnCancelarB.setText("Cancelar");

        GuardarB.setText("Guardar");

        lbCodigoLibro.setText("CodigoLibro");

        txtCodigoLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoLibroActionPerformed(evt);
            }
        });

        txtObservaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtObservacionesActionPerformed(evt);
            }
        });

        lbObeservaciones.setText("Observaciones");

        cbxExistenciaBiblioteca.setText("EXISTENCIA EN BIBLIOTECA LOCAL");
        cbxExistenciaBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxExistenciaBibliotecaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbObeservaciones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbEditor)
                            .addComponent(lbAnio)
                            .addComponent(lbTitulo)
                            .addComponent(lbCiudad)
                            .addComponent(lbAutor))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(282, 282, 282)
                                .addComponent(btnCancelarB)
                                .addGap(18, 18, 18)
                                .addComponent(GuardarB))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEditor, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(CbxAutorCorporativo)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtAutorCorporativo, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbxExistenciaBiblioteca)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(lbTituloVentanaCBApa))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lbCodigoLibro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbTituloVentanaCBApa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxExistenciaBiblioteca)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCodigoLibro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAutor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbxAutorCorporativo)
                    .addComponent(txtAutorCorporativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTitulo)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAnio)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCiudad)
                    .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEditor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbObeservaciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarB)
                    .addComponent(GuardarB))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorActionPerformed

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void txtCodigoLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoLibroActionPerformed

    private void txtEditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditorActionPerformed

    private void txtObservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtObservacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtObservacionesActionPerformed

    private void cbxExistenciaBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxExistenciaBibliotecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxExistenciaBibliotecaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CbxAutorCorporativo;
    public javax.swing.JButton GuardarB;
    public javax.swing.JButton btnCancelarB;
    private javax.swing.JCheckBox cbxExistenciaBiblioteca;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel lbAnio;
    public javax.swing.JLabel lbAutor;
    private javax.swing.JLabel lbCiudad;
    public javax.swing.JLabel lbCodigoLibro;
    private javax.swing.JLabel lbEditor;
    private javax.swing.JLabel lbObeservaciones;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbTituloVentanaCBApa;
    public javax.swing.JTextField txtAnio;
    public javax.swing.JTextField txtAutor;
    public javax.swing.JTextField txtAutorCorporativo;
    public javax.swing.JTextField txtCiudad;
    public javax.swing.JTextField txtCodigoLibro;
    public javax.swing.JTextField txtEditor;
    public javax.swing.JTextField txtObservaciones;
    public javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
