/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.silabos;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author Daniel
 */
public class frmConfiguracionSeguimientoSilabo extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmConfiguracionSeguimientoSilabo
     */
    public frmConfiguracionSeguimientoSilabo() {
        initComponents();
    }

    public JComboBox<String> getCbxAsignatura() {
        return CbxAsignatura;
    }

    public void setCbxAsignatura(JComboBox<String> CbxAsignatura) {
        this.CbxAsignatura = CbxAsignatura;
    }

    public JComboBox<String> getCbxCarrera() {
        return CbxCarrera;
    }

    public void setCbxCarrera(JComboBox<String> CbxCarrera) {
        this.CbxCarrera = CbxCarrera;
    }

    public JComboBox<String> getCbxCurso() {
        return CbxCurso;
    }

    public void setCbxCurso(JComboBox<String> CbxCurso) {
        this.CbxCurso = CbxCurso;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public JButton getBtnSiguiente() {
        return btnSiguiente;
    }

    public void setBtnSiguiente(JButton btnSiguiente) {
        this.btnSiguiente = btnSiguiente;
    }

    public JLabel getLblAsignatura() {
        return lblAsignatura;
    }

    public void setLblAsignatura(JLabel lblAsignatura) {
        this.lblAsignatura = lblAsignatura;
    }

    public JLabel getLblCarrera() {
        return lblCarrera;
    }

    public void setLblCarrera(JLabel lblCarrera) {
        this.lblCarrera = lblCarrera;
    }

    public JLabel getLblConfiguracion() {
        return lblConfiguracion;
    }

    public void setLblConfiguracion(JLabel lblConfiguracion) {
        this.lblConfiguracion = lblConfiguracion;
    }

    public JLabel getLblCurso() {
        return lblCurso;
    }

    public void setLblCurso(JLabel lblCurso) {
        this.lblCurso = lblCurso;
    }

    public JComboBox<String> getCbxPeriodo() {
        return CbxPeriodo;
    }

    public void setCbxPeriodo(JComboBox<String> CbxPeriodo) {
        this.CbxPeriodo = CbxPeriodo;
    }

    public JLabel getLblPeriodo() {
        return lblPeriodo;
    }

    public void setLblPeriodo(JLabel lblPeriodo) {
        this.lblPeriodo = lblPeriodo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CbxCurso = new javax.swing.JComboBox<>();
        lblCurso = new javax.swing.JLabel();
        CbxCarrera = new javax.swing.JComboBox<>();
        lblCarrera = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        lblConfiguracion = new javax.swing.JLabel();
        CbxAsignatura = new javax.swing.JComboBox<>();
        lblAsignatura = new javax.swing.JLabel();
        lblPeriodo = new javax.swing.JLabel();
        CbxPeriodo = new javax.swing.JComboBox<>();

        CbxCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblCurso.setText("Curso:");

        CbxCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblCarrera.setText("Carrera:");

        btnCancelar.setText("Cancelar");

        btnSiguiente.setText("Siguiente");

        lblConfiguracion.setText("Configuracion Seguimiento Silabo");

        CbxAsignatura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblAsignatura.setText("Asignatura:");

        lblPeriodo.setText("Curso:");

        CbxPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 316, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(18, 18, 18)
                .addComponent(btnSiguiente)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addComponent(lblCarrera)
                            .addGap(48, 48, 48)
                            .addComponent(CbxCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addComponent(lblConfiguracion)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CbxPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAsignatura)
                                .addGap(48, 48, 48)
                                .addComponent(CbxAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CbxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCurso)
                                        .addGap(325, 325, 325)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblPeriodo)
                                    .addGap(325, 325, 325))))))
                .addGap(0, 90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConfiguracion)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CbxCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarrera))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbxAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAsignatura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbxPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPeriodo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSiguiente))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbxAsignatura;
    private javax.swing.JComboBox<String> CbxCarrera;
    private javax.swing.JComboBox<String> CbxCurso;
    private javax.swing.JComboBox<String> CbxPeriodo;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel lblAsignatura;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblConfiguracion;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblPeriodo;
    // End of variables declaration//GEN-END:variables
}
