
package vista.silabos;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;


public class frmCRUDBibliografia extends javax.swing.JInternalFrame {

   
    public frmCRUDBibliografia() {
        initComponents();
    }

    public JButton getBtnEditarCB() {
        return btnEditarCB;
    }

    public void setBtnEditarCB(JButton btnEditarCB) {
        this.btnEditarCB = btnEditarCB;
    }

    public JButton getBtnEliminarCB() {
        return btnEliminarCB;
    }

    public void setBtnEliminarCB(JButton btnEliminarCB) {
        this.btnEliminarCB = btnEliminarCB;
    }

    public JButton getBtnNuevoCB() {
        return btnNuevoCB;
    }

    public void setBtnNuevoCB(JButton btnNuevoCB) {
        this.btnNuevoCB = btnNuevoCB;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JLabel getLbBuscarCB() {
        return lbBuscarCB;
    }

    public void setLbBuscarCB(JLabel lbBuscarCB) {
        this.lbBuscarCB = lbBuscarCB;
    }

    public JTable getTblTablaCB() {
        return tblTablaCB;
    }

    public void setTblTablaCB(JTable tblTablaCB) {
        this.tblTablaCB = tblTablaCB;
    }

    public JTextField getTxtBuscarCB() {
        return txtBuscarCB;
    }

    public void setTxtBuscarCB(JTextField txtBuscarCB) {
        this.txtBuscarCB = txtBuscarCB;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTablaCB = new javax.swing.JTable();
        lbBuscarCB = new javax.swing.JLabel();
        txtBuscarCB = new javax.swing.JTextField();
        btnEliminarCB = new javax.swing.JButton();
        btnEditarCB = new javax.swing.JButton();
        btnNuevoCB = new javax.swing.JButton();

        setClosable(true);

        tblTablaCB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Referencia"
            }
        ));
        jScrollPane1.setViewportView(tblTablaCB);
        if (tblTablaCB.getColumnModel().getColumnCount() > 0) {
            tblTablaCB.getColumnModel().getColumn(0).setMinWidth(150);
            tblTablaCB.getColumnModel().getColumn(0).setPreferredWidth(150);
            tblTablaCB.getColumnModel().getColumn(0).setMaxWidth(150);
        }

        lbBuscarCB.setText("Buscar");

        btnEliminarCB.setText("Eliminar");

        btnEditarCB.setText("Editar");

        btnNuevoCB.setText("Nuevo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lbBuscarCB)
                        .addGap(28, 28, 28)
                        .addComponent(txtBuscarCB, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnNuevoCB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarCB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarCB)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBuscarCB)
                    .addComponent(txtBuscarCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarCB)
                    .addComponent(btnEditarCB)
                    .addComponent(btnNuevoCB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEditarCB;
    public javax.swing.JButton btnEliminarCB;
    public javax.swing.JButton btnNuevoCB;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lbBuscarCB;
    public javax.swing.JTable tblTablaCB;
    public javax.swing.JTextField txtBuscarCB;
    // End of variables declaration//GEN-END:variables
}
