/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.silabos;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author Daniel
 */
public class frmConfiguracionSeguimientoSilabo extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmConfiguracionSeguimientoSilabo
     */
    public frmConfiguracionSeguimientoSilabo() {
        initComponents();
        ImageIcon icon = new ImageIcon(ClassLoader.getSystemResource("vista/img/logo.png"));
        this.setFrameIcon(icon);
    }

    

    public JComboBox<String> getCbxCarrera() {
        return CbxCarrera;
    }

    public void setCbxCarrera(JComboBox<String> CbxCarrera) {
        this.CbxCarrera = CbxCarrera;
    }

    public JComboBox<String> getCbxCurso() {
        return CbxCurso;
    }

    public void setCbxCurso(JComboBox<String> CbxCurso) {
        this.CbxCurso = CbxCurso;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public JButton getBtnSiguiente() {
        return btnSiguiente;
    }

    public void setBtnSiguiente(JButton btnSiguiente) {
        this.btnSiguiente = btnSiguiente;
    }

    public JLabel getLblAsignatura() {
        return lblAsignatura;
    }

    public void setLblAsignatura(JLabel lblAsignatura) {
        this.lblAsignatura = lblAsignatura;
    }

    public JLabel getLblCarrera() {
        return lblCarrera;
    }

    public void setLblCarrera(JLabel lblCarrera) {
        this.lblCarrera = lblCarrera;
    }

    public JLabel getLblConfiguracion() {
        return lblConfiguracion;
    }

    public void setLblConfiguracion(JLabel lblConfiguracion) {
        this.lblConfiguracion = lblConfiguracion;
    }

    public JLabel getLblCurso() {
        return lblCurso;
    }

    

    public void setLblCurso(JLabel lblCurso) {
        this.lblCurso = lblCurso;
    }

    public JComboBox<String> getCbxSilabos() {
        return CbxSilabos;
    }

    public void setCbxSilabos(JComboBox<String> CbxSilabos) {
        this.CbxSilabos = CbxSilabos;
    }

    public JComboBox<String> getCmb_perido() {
        return cmb_perido;
    }

    public void setCmb_perido(JComboBox<String> cmb_perido) {
        this.cmb_perido = cmb_perido;
    }

    

    

    public JLabel getLblPeriodo() {
        return lblPeriodo;
    }

    public void setLblPeriodo(JLabel lblPeriodo) {
        this.lblPeriodo = lblPeriodo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CbxCurso = new javax.swing.JComboBox<>();
        lblCurso = new javax.swing.JLabel();
        CbxCarrera = new javax.swing.JComboBox<>();
        lblCarrera = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        lblConfiguracion = new javax.swing.JLabel();
        lblAsignatura = new javax.swing.JLabel();
        lblPeriodo = new javax.swing.JLabel();
        CbxSilabos = new javax.swing.JComboBox<>();
        cmb_perido = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        CbxCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CbxCurso.setName("lista_cursos"); // NOI18N
        CbxCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxCursoActionPerformed(evt);
            }
        });

        lblCurso.setText("Curso:");

        CbxCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CbxCarrera.setName("lista_carreras"); // NOI18N

        lblCarrera.setText("Carrera:");

        btnCancelar.setText("Cancelar");

        btnSiguiente.setText("Siguiente");

        lblConfiguracion.setText("Configuracion Seguimiento Silabo");

        lblAsignatura.setText("Período Lectivo:");

        lblPeriodo.setText("Silabo:");

        CbxSilabos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CbxSilabos.setName("lista_silabos"); // NOI18N

        cmb_perido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_perido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_peridoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(lblPeriodo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CbxSilabos, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblConfiguracion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(btnCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btnSiguiente))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(lblCarrera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CbxCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblAsignatura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb_perido, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(lblCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CbxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblConfiguracion)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarrera)
                    .addComponent(CbxCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAsignatura)
                    .addComponent(cmb_perido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeriodo)
                    .addComponent(CbxSilabos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurso)
                    .addComponent(CbxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar)
                    .addComponent(btnSiguiente)))
        );

        CbxCarrera.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CbxCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbxCursoActionPerformed

    private void cmb_peridoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_peridoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_peridoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbxCarrera;
    private javax.swing.JComboBox<String> CbxCurso;
    private javax.swing.JComboBox<String> CbxSilabos;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox<String> cmb_perido;
    private javax.swing.JLabel lblAsignatura;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblConfiguracion;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblPeriodo;
    // End of variables declaration//GEN-END:variables
}
