/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.silabos;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTable;

/**
 *
 * @author Daniel
 */
public class frmEscogerHorario extends javax.swing.JFrame {

    /**
     * Creates new form frmEscogerHorario
     */
    public frmEscogerHorario() {
        initComponents();
    }

    public JComboBox<String> getCmbxCarreraH() {
        return CmbxCarreraH;
    }

    public void setCmbxCarreraH(JComboBox<String> CmbxCarreraH) {
        this.CmbxCarreraH = CmbxCarreraH;
    }

    public JComboBox<String> getCmbxDocenteH() {
        return CmbxDocenteH;
    }

    public void setCmbxDocenteH(JComboBox<String> CmbxDocenteH) {
        this.CmbxDocenteH = CmbxDocenteH;
    }

    public JComboBox<String> getCmbxJornadaH() {
        return CmbxJornadaH;
    }

    public void setCmbxJornadaH(JComboBox<String> CmbxJornadaH) {
        this.CmbxJornadaH = CmbxJornadaH;
    }

    public JComboBox<String> getCmbxMateriaH() {
        return CmbxMateriaH;
    }

    public void setCmbxMateriaH(JComboBox<String> CmbxMateriaH) {
        this.CmbxMateriaH = CmbxMateriaH;
    }

    public JButton getBtnAgregarH() {
        return btnAgregarH;
    }

    public void setBtnAgregarH(JButton btnAgregarH) {
        this.btnAgregarH = btnAgregarH;
    }

    public JButton getBtnCancelarH() {
        return btnCancelarH;
    }

    public void setBtnCancelarH(JButton btnCancelarH) {
        this.btnCancelarH = btnCancelarH;
    }

    public JButton getBtnGuardarH() {
        return btnGuardarH;
    }

    public void setBtnGuardarH(JButton btnGuardarH) {
        this.btnGuardarH = btnGuardarH;
    }

    public JButton getBtnQuitarH() {
        return btnQuitarH;
    }

    public void setBtnQuitarH(JButton btnQuitarH) {
        this.btnQuitarH = btnQuitarH;
    }

    public JLabel getLbCarreraH() {
        return lbCarreraH;
    }

    public void setLbCarreraH(JLabel lbCarreraH) {
        this.lbCarreraH = lbCarreraH;
    }

    public JLabel getLbDiasH() {
        return lbDiasH;
    }

    public void setLbDiasH(JLabel lbDiasH) {
        this.lbDiasH = lbDiasH;
    }

    public JLabel getLbDocenteH() {
        return lbDocenteH;
    }

    public void setLbDocenteH(JLabel lbDocenteH) {
        this.lbDocenteH = lbDocenteH;
    }

    public JLabel getLbHorarioH() {
        return lbHorarioH;
    }

    public void setLbHorarioH(JLabel lbHorarioH) {
        this.lbHorarioH = lbHorarioH;
    }

    public JLabel getLbJornadaH() {
        return lbJornadaH;
    }

    public void setLbJornadaH(JLabel lbJornadaH) {
        this.lbJornadaH = lbJornadaH;
    }

    public JLabel getLbMateriaH() {
        return lbMateriaH;
    }

    public void setLbMateriaH(JLabel lbMateriaH) {
        this.lbMateriaH = lbMateriaH;
    }

    public JTable getTblHorarioArmadoH() {
        return tblHorarioArmadoH;
    }

    public void setTblHorarioArmadoH(JTable tblHorarioArmadoH) {
        this.tblHorarioArmadoH = tblHorarioArmadoH;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CmbxCarreraH = new javax.swing.JComboBox<>();
        lbCarreraH = new javax.swing.JLabel();
        lbDocenteH = new javax.swing.JLabel();
        btnAgregarH = new javax.swing.JButton();
        btnQuitarH = new javax.swing.JButton();
        btnGuardarH = new javax.swing.JButton();
        btnCancelarH = new javax.swing.JButton();
        lbHorarioH = new javax.swing.JLabel();
        lbDiasH = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHorarioArmadoH = new javax.swing.JTable();
        CmbxDocenteH = new javax.swing.JComboBox<>();
        CmbxMateriaH = new javax.swing.JComboBox<>();
        lbMateriaH = new javax.swing.JLabel();
        CmbxJornadaH = new javax.swing.JComboBox<>();
        lbJornadaH = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CmbxCarreraH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbCarreraH.setText("Carrera");

        lbDocenteH.setText("Docente:");

        btnAgregarH.setText("Agregar");
        btnAgregarH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarHActionPerformed(evt);
            }
        });

        btnQuitarH.setText("Quitar");

        btnGuardarH.setText("Guardar");

        btnCancelarH.setText("Cancelar");

        lbHorarioH.setText("Horario:");

        lbDiasH.setText("Dias:");

        tblHorarioArmadoH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hora", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes"
            }
        ));
        jScrollPane3.setViewportView(tblHorarioArmadoH);

        CmbxDocenteH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CmbxMateriaH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbMateriaH.setText("Materia:");

        CmbxJornadaH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbJornadaH.setText("Jornada");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelarH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardarH, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbMateriaH)
                                    .addComponent(CmbxMateriaH, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbCarreraH)
                                    .addComponent(CmbxCarreraH, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbJornadaH)
                                    .addComponent(CmbxJornadaH, 0, 358, Short.MAX_VALUE)
                                    .addComponent(lbDocenteH)
                                    .addComponent(CmbxDocenteH, 0, 358, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbHorarioH)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbDiasH)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox2, 0, 170, Short.MAX_VALUE)
                                        .addGap(272, 272, 272)))
                                .addComponent(btnAgregarH)
                                .addGap(18, 18, 18)
                                .addComponent(btnQuitarH, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbCarreraH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CmbxCarreraH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMateriaH)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(CmbxMateriaH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(CmbxDocenteH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbDocenteH))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbJornadaH)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(CmbxJornadaH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbHorarioH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarH)
                            .addComponent(btnQuitarH)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbDiasH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarH)
                    .addComponent(btnCancelarH))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEscogerHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEscogerHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEscogerHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEscogerHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEscogerHorario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbxCarreraH;
    private javax.swing.JComboBox<String> CmbxDocenteH;
    private javax.swing.JComboBox<String> CmbxJornadaH;
    private javax.swing.JComboBox<String> CmbxMateriaH;
    private javax.swing.JButton btnAgregarH;
    private javax.swing.JButton btnCancelarH;
    private javax.swing.JButton btnGuardarH;
    private javax.swing.JButton btnQuitarH;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbCarreraH;
    private javax.swing.JLabel lbDiasH;
    private javax.swing.JLabel lbDocenteH;
    private javax.swing.JLabel lbHorarioH;
    private javax.swing.JLabel lbJornadaH;
    private javax.swing.JLabel lbMateriaH;
    private javax.swing.JTable tblHorarioArmadoH;
    // End of variables declaration//GEN-END:variables
}
