package vista.persona;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Lina
 */
public class FrmPersona extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmPersona
     */
    public FrmPersona() {
        initComponents();
    }

    public JLabel getLblErrorCallePrin() {
        return lblErrorCallePrin;
    }

    public JLabel getLblErrorCalleSec() {
        return lblErrorCalleSec;
    }

    public JLabel getLblErrorCanton() {
        return lblErrorCanton;
    }

    public JLabel getLblErrorCantonReside() {
        return lblErrorCantonReside;
    }

    public JLabel getLblErrorCarnetConadis() {
        return lblErrorCarnetConadis;
    }

    public JLabel getLblErrorCelular() {
        return lblErrorCelular;
    }

    public JLabel getLblErrorCodigoPostal() {
        return lblErrorCodigoPostal;
    }

    public JLabel getLblErrorCorreo() {
        return lblErrorCorreo;
    }

    public JLabel getLblErrorEstadoCivil() {
        return lblErrorEstadoCivil;
    }

    public JLabel getLblErrorEtnia() {
        return lblErrorEtnia;
    }

    public JLabel getLblErrorFecNac() {
        return lblErrorFecNac;
    }

    public JDateChooser getJdfechaNacimiento() {
        return jdfechaNacimiento;
    }

    public void setJdfechaNacimiento(JDateChooser jdfechaNacimiento) {
        this.jdfechaNacimiento = jdfechaNacimiento;
    }

    public JLabel getLblErrorGenero() {
        return lblErrorGenero;
    }

    public JLabel getLblErrorIdentificacion() {
        return lblErrorIdentificacion;
    }

    public JLabel getLblErrorIdioma() {
        return lblErrorIdioma;
    }

    public JLabel getLblErrorNacionalidad() {
        return lblErrorNacionalidad;
    }

    public JLabel getLblErrorNumeroCasa() {
        return lblErrorNumeroCasa;
    }

    public JLabel getLblErrorParroquiaReside() {
        return lblErrorParroquiaReside;
    }

    public JLabel getLblErrorPorcentaje() {
        return lblErrorPorcentaje;
    }

    public JLabel getLblErrorPriApellido() {
        return lblErrorPriApellido;
    }

    public JLabel getLblErrorPriNombre() {
        return lblErrorPriNombre;
    }

    public JLabel getLblErrorProvincia() {
        return lblErrorProvincia;
    }

    public JLabel getLblErrorProvinciaReside() {
        return lblErrorProvinciaReside;
    }

    public JLabel getLblErrorReferencia() {
        return lblErrorReferencia;
    }

    public JLabel getLblErrorSector() {
        return lblErrorSector;
    }

    public JLabel getLblErrorSegApellido() {
        return lblErrorSegApellido;
    }

    public JLabel getLblErrorSegNombre() {
        return lblErrorSegNombre;
    }

    public JLabel getLblErrorSexo() {
        return lblErrorSexo;
    }

    public JLabel getLblErrorTelefono() {
        return lblErrorTelefono;
    }

    public JLabel getLblErrorTipoDiscapacidad() {
        return lblErrorTipoDiscapacidad;
    }

    public JLabel getLblErrorTipoResidencia() {
        return lblErrorTipoResidencia;
    }

    public JLabel getLblErrorTipoSangre() {
        return lblErrorTipoSangre;
    }

    public JComboBox<String> getCmbPaisReside() {
        return cmbPaisReside;
    }

    public JLabel getLblErrorPaisReside() {
        return lblErrorPaisReside;
    }

    public JComboBox<String> getCmbIdiomas() {
        return cmbIdiomas;
    }


  


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbTipoId = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbSexo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cmbEstadoCivil = new javax.swing.JComboBox<>();
        txtSegundoApellido = new javax.swing.JTextField();
        txtPrimerApellido = new javax.swing.JTextField();
        txtPrimerNombre = new javax.swing.JTextField();
        txtSegundoNombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cmbEtnia = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cmbGenero = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cmbTipoSangre = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        lblTipoDiscapacidad = new javax.swing.JLabel();
        cmbTipoDiscapacidad = new javax.swing.JComboBox<>();
        lblPorcentaje = new javax.swing.JLabel();
        txtPorcentaje = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblCarnetConadis = new javax.swing.JLabel();
        txtCarnetConadis = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        cbxDiscapacidad = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        cmbProvincia = new javax.swing.JComboBox<>();
        cmbNacionalidad = new javax.swing.JComboBox<>();
        cmbCanton = new javax.swing.JComboBox<>();
        txtCodigoPostal = new javax.swing.JTextField();
        cmbProvinciaReside = new javax.swing.JComboBox<>();
        cmbCantonReside = new javax.swing.JComboBox<>();
        cmbParroquiaReside = new javax.swing.JComboBox<>();
        txtCallePrincipal = new javax.swing.JTextField();
        txtReferencia = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtNumeroCasa = new javax.swing.JTextField();
        txtSector = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtCalleSecundaria = new javax.swing.JTextField();
        cmbTipoResidencia = new javax.swing.JComboBox<>();
        btnGuardarPersona = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        lblFoto = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        btnBuscarFoto = new javax.swing.JButton();
        btnBuscarPersona = new javax.swing.JButton();
        lblErrorCelular = new javax.swing.JLabel();
        lblErrorIdentificacion = new javax.swing.JLabel();
        lblErrorPorcentaje = new javax.swing.JLabel();
        lblErrorTipoSangre = new javax.swing.JLabel();
        lblErrorPriApellido = new javax.swing.JLabel();
        lblErrorSegNombre = new javax.swing.JLabel();
        lblErrorEtnia = new javax.swing.JLabel();
        lblErrorFecNac = new javax.swing.JLabel();
        lblErrorSexo = new javax.swing.JLabel();
        lblErrorIdioma = new javax.swing.JLabel();
        lblErrorCanton = new javax.swing.JLabel();
        lblErrorCarnetConadis = new javax.swing.JLabel();
        lblErrorGenero = new javax.swing.JLabel();
        lblErrorTipoDiscapacidad = new javax.swing.JLabel();
        lblErrorParroquiaReside = new javax.swing.JLabel();
        lblErrorProvincia = new javax.swing.JLabel();
        lblErrorNacionalidad = new javax.swing.JLabel();
        lblErrorCorreo = new javax.swing.JLabel();
        lblErrorNumeroCasa = new javax.swing.JLabel();
        lblErrorProvinciaReside = new javax.swing.JLabel();
        lblErrorCallePrin = new javax.swing.JLabel();
        lblErrorCalleSec = new javax.swing.JLabel();
        lblErrorCantonReside = new javax.swing.JLabel();
        lblErrorCodigoPostal = new javax.swing.JLabel();
        lblErrorReferencia = new javax.swing.JLabel();
        lblErrorSector = new javax.swing.JLabel();
        lblErrorTipoResidencia = new javax.swing.JLabel();
        lblErrorSegApellido = new javax.swing.JLabel();
        lblErrorTelefono = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        lblErrorEstadoCivil = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        cmbPaisReside = new javax.swing.JComboBox<>();
        lblErrorPaisReside = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cmbIdiomas = new javax.swing.JComboBox<>();
        lblErrorPriNombre = new javax.swing.JLabel();
        btnCapturarFoto = new javax.swing.JButton();
        jdfechaNacimiento = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        setTitle("CREAR NUEVA PERSONA");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbTipoId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "CEDULA", "PASAPORTE" }));
        cmbTipoId.setBorder(null);
        getContentPane().add(cmbTipoId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 130, -1));

        jLabel2.setText("Identificacion *");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, 20));
        getContentPane().add(txtIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 130, -1));

        jLabel3.setText("Primer Apellido *");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 103, 20));

        jLabel4.setText("Segundo Apellido");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 100, 20));

        jLabel5.setText("Fecha Nacimiento *");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 130, 20));

        jLabel6.setText("Primer Nombre *");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 103, 20));

        jLabel7.setText("Segundo Nombre");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 90, 20));

        jLabel8.setText("Sexo *");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 20));

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "HOMBRE", "MUJER" }));
        getContentPane().add(cmbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 130, -1));

        jLabel9.setText("Estado Civil *");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, -1, 20));

        cmbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "SOLTERO/A", "CASADO/A", "DIVORCIADO/A", "UNION LIBRE", "VIUDO/A" }));
        getContentPane().add(cmbEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 133, -1));
        getContentPane().add(txtSegundoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 130, -1));
        getContentPane().add(txtPrimerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 130, -1));
        getContentPane().add(txtPrimerNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 130, -1));
        getContentPane().add(txtSegundoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 130, -1));

        jLabel10.setText("Etnia *");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, 20));

        cmbEtnia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "INDIGENA", "MESTIZO", "MULATO", "AFRO-ECUATORIANO", "BLANCO", "AWA", "ACHUAR", "CHACHI", "COFÁN", "SECOYA", "SHIWIAR", "SHUAR", "TSACHILA", "WAORANI", "ANDOA", "KICHWA DE LA SIERRA", "PASTOS", "OTAVALO", "KARANKI", "KAYAMBI", "CHIBULEOSALASAKA", "KISAPINCHA", "PURUHÁ", "KAÑARI", "SARAGURO", "PALTAS", "HUANCAVILCA", "OTRA ETNIA", "SE IGNORA" }));
        getContentPane().add(cmbEtnia, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 130, 20));

        jLabel11.setText("Genero *");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, 20));

        cmbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "MASCULINO", "FEMENINO", "LGBTI" }));
        getContentPane().add(cmbGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 130, -1));

        jLabel12.setText("Tipo Sangre *");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 20));

        cmbTipoSangre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "O+", "O-", "A+", "A-", "B+", "B-", "AB+", "AB-" }));
        getContentPane().add(cmbTipoSangre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 130, -1));

        jLabel13.setText("Discapacidad");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, 20));

        lblTipoDiscapacidad.setText("Tipo de discapacidad");
        getContentPane().add(lblTipoDiscapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, 20));

        cmbTipoDiscapacidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "FÍSICA", "INTELECTUAL", "SENSORIAL", "PSÍQUICA", "VISCERAL", "MULTIPLE" }));
        getContentPane().add(cmbTipoDiscapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 160, -1));

        lblPorcentaje.setText("Porcentaje");
        getContentPane().add(lblPorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, -1, 20));
        getContentPane().add(txtPorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, 30, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1040, 10));

        lblCarnetConadis.setText("Carnet Conadis");
        getContentPane().add(lblCarnetConadis, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, 20));
        getContentPane().add(txtCarnetConadis, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 120, -1));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 1020, 10));

        jLabel17.setText("Seleccione su idioma *");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 130, 20));

        cbxDiscapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDiscapacidadActionPerformed(evt);
            }
        });
        getContentPane().add(cbxDiscapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        jLabel19.setText("Telefono");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, 20));

        jLabel20.setText("Celular");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 20));

        jLabel21.setText("Correo");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, -1, 20));
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 130, -1));
        getContentPane().add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 128, -1));
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 260, -1));

        jLabel23.setText("Pais Reside *");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 80, 20));

        jLabel24.setText("Canton Reside *");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, 100, 20));

        jLabel25.setText("Parroquia Reside *");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 110, 20));

        jLabel26.setText("Codigo Postal *");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 90, 20));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 322, 515, 0));

        jLabel27.setText("Calle Principal *");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 90, 20));

        jLabel28.setText("Referencia");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 80, 20));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 1030, 10));

        jLabel29.setText("Nacionalidad *");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 100, 20));

        jLabel30.setText("Provincia *");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 70, 20));

        jLabel31.setText("Canton *");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, 60, 20));

        cmbProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE" }));
        getContentPane().add(cmbProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 230, -1));

        cmbNacionalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "ECUATORIANO/A", "COLOMBIANO/A", "PERUANO/A", "VENEZOLANO/A", " " }));
        getContentPane().add(cmbNacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 200, -1));

        cmbCanton.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE" }));
        getContentPane().add(cmbCanton, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 310, 230, -1));
        getContentPane().add(txtCodigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 250, -1));

        cmbProvinciaReside.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE" }));
        getContentPane().add(cmbProvinciaReside, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 230, -1));

        cmbCantonReside.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE" }));
        getContentPane().add(cmbCantonReside, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 360, 230, -1));

        cmbParroquiaReside.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE" }));
        getContentPane().add(cmbParroquiaReside, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 310, -1));
        getContentPane().add(txtCallePrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 310, -1));
        getContentPane().add(txtReferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 460, -1));

        jLabel32.setText("Numero Casa");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 480, -1, 20));

        jLabel33.setText("Sector");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, 60, 20));
        getContentPane().add(txtNumeroCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 480, 50, -1));
        getContentPane().add(txtSector, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, 250, -1));

        jLabel34.setText("Calle Secundaria");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 90, 20));

        jLabel35.setText("Tipo Residencia *");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 400, 100, 20));
        getContentPane().add(txtCalleSecundaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 310, -1));

        cmbTipoResidencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "ZONA URBANA", "ZONA RURAL" }));
        getContentPane().add(cmbTipoResidencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 400, 90, -1));

        btnGuardarPersona.setText("Guardar");
        getContentPane().add(btnGuardarPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 530, -1, -1));

        btnCancelar.setText("Cancelar");
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 530, -1, -1));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 1030, 10));

        lblFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        getContentPane().add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 70, 160, 180));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, 10, 260));

        btnBuscarFoto.setText("Buscar Foto");
        getContentPane().add(btnBuscarFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 260, 100, -1));

        btnBuscarPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/icons8_Search_15px.png"))); // NOI18N
        getContentPane().add(btnBuscarPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 30, 20));

        lblErrorCelular.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorCelular.setText("Ingrese un número de celular válido");
        getContentPane().add(lblErrorCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 240, -1));

        lblErrorIdentificacion.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorIdentificacion.setText("Ingrese 10 digitos");
        getContentPane().add(lblErrorIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 190, 20));

        lblErrorPorcentaje.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorPorcentaje.setText("Solo debe ingresar numeros");
        getContentPane().add(lblErrorPorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 130, -1));

        lblErrorTipoSangre.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorTipoSangre.setText("Seleccione su tipo de sangre");
        getContentPane().add(lblErrorTipoSangre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 240, -1));

        lblErrorPriApellido.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorPriApellido.setText("Solo debe ingresar letras.");
        getContentPane().add(lblErrorPriApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 240, -1));

        lblErrorSegNombre.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorSegNombre.setText("Solo debe ingresar letras.");
        getContentPane().add(lblErrorSegNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 240, -1));

        lblErrorEtnia.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorEtnia.setText("Seleccione su etnia");
        getContentPane().add(lblErrorEtnia, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 240, -1));

        lblErrorFecNac.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorFecNac.setText("Seleccione su fecha de nacimiento");
        getContentPane().add(lblErrorFecNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 240, -1));

        lblErrorSexo.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorSexo.setText("Seleccione su sexo");
        getContentPane().add(lblErrorSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 240, -1));

        lblErrorIdioma.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorIdioma.setText("Seleccione su idioma");
        getContentPane().add(lblErrorIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 240, -1));

        lblErrorCanton.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorCanton.setText("Seleccione su cantón");
        getContentPane().add(lblErrorCanton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 280, -1));

        lblErrorCarnetConadis.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorCarnetConadis.setText("Solo debe ingresar numeros");
        getContentPane().add(lblErrorCarnetConadis, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 210, -1));

        lblErrorGenero.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorGenero.setText("Seleccione su genero");
        getContentPane().add(lblErrorGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 240, -1));

        lblErrorTipoDiscapacidad.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorTipoDiscapacidad.setText("Seleccione su tipo de discapacidad");
        getContentPane().add(lblErrorTipoDiscapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 270, -1));

        lblErrorParroquiaReside.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorParroquiaReside.setText("Seleccione su parroquia que reside");
        getContentPane().add(lblErrorParroquiaReside, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 420, -1));

        lblErrorProvincia.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorProvincia.setText("Seleccione su provincia");
        getContentPane().add(lblErrorProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 290, -1));

        lblErrorNacionalidad.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorNacionalidad.setText("Seleccione su nacionalidad");
        getContentPane().add(lblErrorNacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 340, -1));

        lblErrorCorreo.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorCorreo.setText("Ingrese un correo válido");
        getContentPane().add(lblErrorCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 240, -1));

        lblErrorNumeroCasa.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorNumeroCasa.setText("Ejemplo: 4-32  ó  s/n");
        getContentPane().add(lblErrorNumeroCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 500, 190, -1));

        lblErrorProvinciaReside.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorProvinciaReside.setText("Seleccione su provincia que reside");
        getContentPane().add(lblErrorProvinciaReside, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 310, -1));

        lblErrorCallePrin.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorCallePrin.setText("Solo debe ingresar numeros y letras");
        getContentPane().add(lblErrorCallePrin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 440, -1));

        lblErrorCalleSec.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorCalleSec.setText("Solo debe ingresar numeros y letras");
        getContentPane().add(lblErrorCalleSec, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 440, -1));

        lblErrorCantonReside.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorCantonReside.setText("Seleccione su canton que reside");
        getContentPane().add(lblErrorCantonReside, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 380, 320, -1));

        lblErrorCodigoPostal.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorCodigoPostal.setText("Solo debe ingresar numeros");
        getContentPane().add(lblErrorCodigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 290, -1));

        lblErrorReferencia.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorReferencia.setText("Solo debe ingresar letras.");
        getContentPane().add(lblErrorReferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, 540, -1));

        lblErrorSector.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorSector.setText("Solo debe ingresar letras.");
        getContentPane().add(lblErrorSector, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, 290, -1));

        lblErrorTipoResidencia.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorTipoResidencia.setText("Seleccione su tipo de residencia");
        getContentPane().add(lblErrorTipoResidencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 420, 190, -1));

        lblErrorSegApellido.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorSegApellido.setText("Solo debe ingresar letras.");
        getContentPane().add(lblErrorSegApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 240, -1));

        lblErrorTelefono.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorTelefono.setText("Ingrese un número de telefono válido");
        getContentPane().add(lblErrorTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 240, -1));
        getContentPane().add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 790, 10));

        lblErrorEstadoCivil.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorEstadoCivil.setText("Seleccione un estado civil");
        getContentPane().add(lblErrorEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 240, -1));

        jLabel36.setText("Provincia Reside *");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 100, 20));

        cmbPaisReside.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE" }));
        getContentPane().add(cmbPaisReside, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 200, -1));

        lblErrorPaisReside.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorPaisReside.setText("Seleccione su pais de residencia");
        getContentPane().add(lblErrorPaisReside, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 310, -1));

        jLabel18.setText("Tipo de Identificación*");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 10, 110, 20));

        cmbIdiomas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE" }));
        getContentPane().add(cmbIdiomas, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 130, -1));

        lblErrorPriNombre.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorPriNombre.setText("Solo debe ingresar letras.");
        getContentPane().add(lblErrorPriNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 240, -1));

        btnCapturarFoto.setText("Capturar Foto");
        getContentPane().add(btnCapturarFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 260, -1, -1));
        getContentPane().add(jdfechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxDiscapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDiscapacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDiscapacidadActionPerformed

    public JButton getBtnBuscarPersona() {
        return btnBuscarPersona;
    }

    public void setBtnBuscarPersona(JButton btnBuscarPersona) {
        this.btnBuscarPersona = btnBuscarPersona;
    }

    public JButton getBtnBuscarFoto() {
        return btnBuscarFoto;
    }
    
    public void setBtnBuscarFoto(JButton btnBuscarFoto) {
        this.btnBuscarFoto = btnBuscarFoto;
    }

    public JButton getBtnCapturarFoto() {
        return btnCapturarFoto;
    }

    public void setBtnCapturarFoto(JButton btnCapturarFoto) {
        this.btnCapturarFoto = btnCapturarFoto;
    }
  
    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public JButton getBtnGuardarPersona() {
        return btnGuardarPersona;
    }

    public void setBtnGuardarPersona(JButton btnGuardarPersona) {
        this.btnGuardarPersona = btnGuardarPersona;
    }

    public JCheckBox getCbxDiscapacidad() {
        return cbxDiscapacidad;
    }

    public void setCbxDiscapacidad(JCheckBox cbxDiscapacidad) {
        this.cbxDiscapacidad = cbxDiscapacidad;
    }

    public JComboBox<String> getCmbCanton() {
        return cmbCanton;
    }

    public void setCmbCanton(JComboBox<String> cmbCanton) {
        this.cmbCanton = cmbCanton;
    }

    public JComboBox<String> getCmbCantonReside() {
        return cmbCantonReside;
    }

    public void setCmbCantonReside(JComboBox<String> cmbCantonReside) {
        this.cmbCantonReside = cmbCantonReside;
    }

    public JComboBox<String> getCmbEstadoCivil() {
        return cmbEstadoCivil;
    }

    public void setCmbEstadoCivil(JComboBox<String> cmbEstadoCivil) {
        this.cmbEstadoCivil = cmbEstadoCivil;
    }

    public JComboBox<String> getCmbEtnia() {
        return cmbEtnia;
    }

    public void setCmbEtnia(JComboBox<String> cmbEtnia) {
        this.cmbEtnia = cmbEtnia;
    }

    public JComboBox<String> getCmbGenero() {
        return cmbGenero;
    }

    public void setCmbGenero(JComboBox<String> cmbGenero) {
        this.cmbGenero = cmbGenero;
    }

    public JComboBox<String> getCmbNacionalidad() {
        return cmbNacionalidad;
    }

    public void setCmbNacionalidad(JComboBox<String> cmbNacionalidad) {
        this.cmbNacionalidad = cmbNacionalidad;
    }

    public JComboBox<String> getCmbParroquiaReside() {
        return cmbParroquiaReside;
    }

    public void setCmbParroquiaReside(JComboBox<String> cmbParroquiaReside) {
        this.cmbParroquiaReside = cmbParroquiaReside;
    }

    public JComboBox<String> getCmbProvincia() {
        return cmbProvincia;
    }

    public void setCmbProvincia(JComboBox<String> cmbProvincia) {
        this.cmbProvincia = cmbProvincia;
    }

    public JComboBox<String> getCmbProvinciaReside() {
        return cmbProvinciaReside;
    }

    public void setCmbProvinciaReside(JComboBox<String> cmbProvinciaReside) {
        this.cmbProvinciaReside = cmbProvinciaReside;
    }

    public JComboBox<String> getCmbSexo() {
        return cmbSexo;
    }

    public void setCmbSexo(JComboBox<String> cmbSexo) {
        this.cmbSexo = cmbSexo;
    }

    public JComboBox<String> getCmbTipoDiscapacidad() {
        return cmbTipoDiscapacidad;
    }

    public void setCmbTipoDiscapacidad(JComboBox<String> cmbTipoDiscapacidad) {
        this.cmbTipoDiscapacidad = cmbTipoDiscapacidad;
    }

    public JComboBox<String> getCmbTipoId() {
        return cmbTipoId;
    }

    public void setCmbTipoId(JComboBox<String> cmbTipoId) {
        this.cmbTipoId = cmbTipoId;
    }

    public JComboBox<String> getCmbTipoResidencia() {
        return cmbTipoResidencia;
    }

    public void setCmbTipoResidencia(JComboBox<String> cmbTipoResidencia) {
        this.cmbTipoResidencia = cmbTipoResidencia;
    }

    public JComboBox<String> getCmbTipoSangre() {
        return cmbTipoSangre;
    }

    public void setCmbTipoSangre(JComboBox<String> cmbTipoSangre) {
        this.cmbTipoSangre = cmbTipoSangre;
    }

    public JLabel getojLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public void setjLabel11(JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    public JLabel getjLabel12() {
        return jLabel12;
    }

    public void setjLabel12(JLabel jLabel12) {
        this.jLabel12 = jLabel12;
    }

    public JLabel getjLabel13() {
        return jLabel13;
    }

    public void setjLabel13(JLabel jLabel13) {
        this.jLabel13 = jLabel13;
    }

    public JLabel getLblCarnetConadis() {
        return lblCarnetConadis;
    }

    public void setLblCarnetConadis(JLabel lblCarnetConadis) {
        this.lblCarnetConadis = lblCarnetConadis;
    }

    public JLabel getLblPorcentaje() {
        return lblPorcentaje;
    }

    public void setLblPorcentaje(JLabel lblPorcentaje) {
        this.lblPorcentaje = lblPorcentaje;
    }

    public JLabel getLblTipoDiscapacidad() {
        return lblTipoDiscapacidad;
    }

    public void setLblTipoDiscapacidad(JLabel lblTipoDiscapacidad) {
        this.lblTipoDiscapacidad = lblTipoDiscapacidad;
    }

   

    public JLabel getjLabel17() {
        return jLabel17;
    }

    public void setjLabel17(JLabel jLabel17) {
        this.jLabel17 = jLabel17;
    }

    public JLabel getjLabel19() {
        return jLabel19;
    }

    public void setjLabel19(JLabel jLabel19) {
        this.jLabel19 = jLabel19;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel20() {
        return jLabel20;
    }

    public void setjLabel20(JLabel jLabel20) {
        this.jLabel20 = jLabel20;
    }

    public JLabel getjLabel21() {
        return jLabel21;
    }

    public void setjLabel21(JLabel jLabel21) {
        this.jLabel21 = jLabel21;
    }

    public JLabel getjLabel22() {
        return lblErrorIdentificacion;
    }

    public void setjLabel22(JLabel jLabel22) {
        this.lblErrorIdentificacion = jLabel22;
    }

    public JLabel getjLabel23() {
        return jLabel23;
    }

    public void setjLabel23(JLabel jLabel23) {
        this.jLabel23 = jLabel23;
    }

    public JLabel getjLabel24() {
        return jLabel24;
    }

    public void setjLabel24(JLabel jLabel24) {
        this.jLabel24 = jLabel24;
    }

    public JLabel getjLabel25() {
        return jLabel25;
    }

    public void setjLabel25(JLabel jLabel25) {
        this.jLabel25 = jLabel25;
    }

    public JLabel getjLabel26() {
        return jLabel26;
    }

    public void setjLabel26(JLabel jLabel26) {
        this.jLabel26 = jLabel26;
    }

    public JLabel getjLabel27() {
        return jLabel27;
    }

    public void setjLabel27(JLabel jLabel27) {
        this.jLabel27 = jLabel27;
    }

    public JLabel getjLabel28() {
        return jLabel28;
    }

    public void setjLabel28(JLabel jLabel28) {
        this.jLabel28 = jLabel28;
    }

    public JLabel getjLabel29() {
        return jLabel29;
    }

    public void setjLabel29(JLabel jLabel29) {
        this.jLabel29 = jLabel29;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel30() {
        return jLabel30;
    }

    public void setjLabel30(JLabel jLabel30) {
        this.jLabel30 = jLabel30;
    }

    public JLabel getjLabel31() {
        return jLabel31;
    }

    public void setjLabel31(JLabel jLabel31) {
        this.jLabel31 = jLabel31;
    }

    public JLabel getjLabel32() {
        return jLabel32;
    }

    public void setjLabel32(JLabel jLabel32) {
        this.jLabel32 = jLabel32;
    }

    public JLabel getjLabel33() {
        return jLabel33;
    }

    public void setjLabel33(JLabel jLabel33) {
        this.jLabel33 = jLabel33;
    }

    public JLabel getjLabel34() {
        return jLabel34;
    }

    public void setjLabel34(JLabel jLabel34) {
        this.jLabel34 = jLabel34;
    }

    public JLabel getjLabel35() {
        return jLabel35;
    }

    public void setjLabel35(JLabel jLabel35) {
        this.jLabel35 = jLabel35;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

//    public DateChooserCombo getJdcFechaNacimiento() {
//        return jdcFechaNacimiento;
//    }
//
//    public void setJdcFechaNacimiento(DateChooserCombo jdcFechaNacimiento) {
//        this.jdcFechaNacimiento = jdcFechaNacimiento;
//    }

    public JLabel getLblFoto() {
        return lblFoto;
    }

    public void setLblFoto(JLabel lblFoto) {
        this.lblFoto = lblFoto;
    }

    public JTextField getTxtCallePrincipal() {
        return txtCallePrincipal;
    }

    public void setTxtCallePrincipal(JTextField txtCallePrincipal) {
        this.txtCallePrincipal = txtCallePrincipal;
    }

    public JTextField getTxtCalleSecundaria() {
        return txtCalleSecundaria;
    }

    public void setTxtCalleSecundaria(JTextField txtCalleSecundaria) {
        this.txtCalleSecundaria = txtCalleSecundaria;
    }

    public JTextField getTxtCarnetConadis() {
        return txtCarnetConadis;
    }

    public void setTxtCarnetConadis(JTextField txtCarnetConadis) {
        this.txtCarnetConadis = txtCarnetConadis;
    }

    public JTextField getTxtCelular() {
        return txtCelular;
    }

    public void setTxtCelular(JTextField txtCelular) {
        this.txtCelular = txtCelular;
    }

    public JTextField getTxtCodigoPostal() {
        return txtCodigoPostal;
    }

    public void setTxtCodigoPostal(JTextField txtCodigoPostal) {
        this.txtCodigoPostal = txtCodigoPostal;
    }

    public JTextField getTxtCorreo() {
        return txtCorreo;
    }

    public void setTxtCorreo(JTextField txtCorreo) {
        this.txtCorreo = txtCorreo;
    }

    public JTextField getTxtIdentificacion() {
        return txtIdentificacion;
    }

    public void setTxtIdentificacion(JTextField txtIdentificacion) {
        this.txtIdentificacion = txtIdentificacion;
    }

    public JTextField getTxtNumeroCasa() {
        return txtNumeroCasa;
    }

    public void setTxtNumeroCasa(JTextField txtNumeroCasa) {
        this.txtNumeroCasa = txtNumeroCasa;
    }

    public JTextField getTxtPorcentaje() {
        return txtPorcentaje;
    }

    public void setTxtPorcentaje(JTextField txtPorcentaje) {
        this.txtPorcentaje = txtPorcentaje;
    }

    public JTextField getTxtPrimerApellido() {
        return txtPrimerApellido;
    }

    public void setTxtPrimerApellido(JTextField txtPrimerApellido) {
        this.txtPrimerApellido = txtPrimerApellido;
    }

    public JTextField getTxtPrimerNombre() {
        return txtPrimerNombre;
    }

    public void setTxtPrimerNombre(JTextField txtPrimerNombre) {
        this.txtPrimerNombre = txtPrimerNombre;
    }

    public JTextField getTxtReferencia() {
        return txtReferencia;
    }

    public void setTxtReferencia(JTextField txtReferencia) {
        this.txtReferencia = txtReferencia;
    }

    public JTextField getTxtSector() {
        return txtSector;
    }

    public void setTxtSector(JTextField txtSector) {
        this.txtSector = txtSector;
    }

    public JTextField getTxtSegundoApellido() {
        return txtSegundoApellido;
    }

    public void setTxtSegundoApellido(JTextField txtSegundoApellido) {
        this.txtSegundoApellido = txtSegundoApellido;
    }

    public JTextField getTxtSegundoNombre() {
        return txtSegundoNombre;
    }

    public void setTxtSegundoNombre(JTextField txtSegundoNombre) {
        this.txtSegundoNombre = txtSegundoNombre;
    }

    public JTextField getTxtTelefono() {
        return txtTelefono;
    }

    public void setTxtTelefono(JTextField txtTelefono) {
        this.txtTelefono = txtTelefono;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarFoto;
    private javax.swing.JButton btnBuscarPersona;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCapturarFoto;
    private javax.swing.JButton btnGuardarPersona;
    private javax.swing.JCheckBox cbxDiscapacidad;
    private javax.swing.JComboBox<String> cmbCanton;
    private javax.swing.JComboBox<String> cmbCantonReside;
    private javax.swing.JComboBox<String> cmbEstadoCivil;
    private javax.swing.JComboBox<String> cmbEtnia;
    private javax.swing.JComboBox<String> cmbGenero;
    private javax.swing.JComboBox<String> cmbIdiomas;
    private javax.swing.JComboBox<String> cmbNacionalidad;
    private javax.swing.JComboBox<String> cmbPaisReside;
    private javax.swing.JComboBox<String> cmbParroquiaReside;
    private javax.swing.JComboBox<String> cmbProvincia;
    private javax.swing.JComboBox<String> cmbProvinciaReside;
    private javax.swing.JComboBox<String> cmbSexo;
    private javax.swing.JComboBox<String> cmbTipoDiscapacidad;
    private javax.swing.JComboBox<String> cmbTipoId;
    private javax.swing.JComboBox<String> cmbTipoResidencia;
    private javax.swing.JComboBox<String> cmbTipoSangre;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private com.toedter.calendar.JDateChooser jdfechaNacimiento;
    private javax.swing.JLabel lblCarnetConadis;
    private javax.swing.JLabel lblErrorCallePrin;
    private javax.swing.JLabel lblErrorCalleSec;
    private javax.swing.JLabel lblErrorCanton;
    private javax.swing.JLabel lblErrorCantonReside;
    private javax.swing.JLabel lblErrorCarnetConadis;
    private javax.swing.JLabel lblErrorCelular;
    private javax.swing.JLabel lblErrorCodigoPostal;
    private javax.swing.JLabel lblErrorCorreo;
    private javax.swing.JLabel lblErrorEstadoCivil;
    private javax.swing.JLabel lblErrorEtnia;
    private javax.swing.JLabel lblErrorFecNac;
    private javax.swing.JLabel lblErrorGenero;
    private javax.swing.JLabel lblErrorIdentificacion;
    private javax.swing.JLabel lblErrorIdioma;
    private javax.swing.JLabel lblErrorNacionalidad;
    private javax.swing.JLabel lblErrorNumeroCasa;
    private javax.swing.JLabel lblErrorPaisReside;
    private javax.swing.JLabel lblErrorParroquiaReside;
    private javax.swing.JLabel lblErrorPorcentaje;
    private javax.swing.JLabel lblErrorPriApellido;
    private javax.swing.JLabel lblErrorPriNombre;
    private javax.swing.JLabel lblErrorProvincia;
    private javax.swing.JLabel lblErrorProvinciaReside;
    private javax.swing.JLabel lblErrorReferencia;
    private javax.swing.JLabel lblErrorSector;
    private javax.swing.JLabel lblErrorSegApellido;
    private javax.swing.JLabel lblErrorSegNombre;
    private javax.swing.JLabel lblErrorSexo;
    private javax.swing.JLabel lblErrorTelefono;
    private javax.swing.JLabel lblErrorTipoDiscapacidad;
    private javax.swing.JLabel lblErrorTipoResidencia;
    private javax.swing.JLabel lblErrorTipoSangre;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblPorcentaje;
    private javax.swing.JLabel lblTipoDiscapacidad;
    private javax.swing.JTextField txtCallePrincipal;
    private javax.swing.JTextField txtCalleSecundaria;
    private javax.swing.JTextField txtCarnetConadis;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCodigoPostal;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNumeroCasa;
    private javax.swing.JTextField txtPorcentaje;
    private javax.swing.JTextField txtPrimerApellido;
    private javax.swing.JTextField txtPrimerNombre;
    private javax.swing.JTextField txtReferencia;
    private javax.swing.JTextField txtSector;
    private javax.swing.JTextField txtSegundoApellido;
    private javax.swing.JTextField txtSegundoNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
