package vista.persona;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Lina
 */
public class FrmPersona extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmPersona
     */
    public FrmPersona() {
        initComponents();
    }

    public JLabel getLblErrorCallePrin() {
        return lblErrorCallePrin;
    }

    public JLabel getLblErrorCalleSec() {
        return lblErrorCalleSec;
    }

    public JLabel getLblErrorCanton() {
        return lblErrorCanton;
    }

    public JLabel getLblErrorCantonReside() {
        return lblErrorCantonReside;
    }

    public JLabel getLblErrorCarnetConadis() {
        return lblErrorCarnetConadis;
    }

    public JLabel getLblErrorCelular() {
        return lblErrorCelular;
    }

    public JLabel getLblErrorCodigoPostal() {
        return lblErrorCodigoPostal;
    }

    public JLabel getLblErrorCorreo() {
        return lblErrorCorreo;
    }

    public JLabel getLblErrorEstadoCivil() {
        return lblErrorEstadoCivil;
    }

    public JLabel getLblErrorEtnia() {
        return lblErrorEtnia;
    }

    public JLabel getLblErrorFecNac() {
        return lblErrorFecNac;
    }

    public JDateChooser getJdfechaNacimiento() {
        return jdfechaNacimiento;
    }

    public void setJdfechaNacimiento(JDateChooser jdfechaNacimiento) {
        this.jdfechaNacimiento = jdfechaNacimiento;
    }

    public JCheckBox getCbxCategoriaMigratoria() {
        return cbxCategoriaMigratoria;
    }

    public void setCbxCategoriaMigratoria(JCheckBox cbxCategoriaMigratoria) {
        this.cbxCategoriaMigratoria = cbxCategoriaMigratoria;
    }

    public JComboBox<String> getCmbCategoriaMigratoria() {
        return cmbCategoriaMigratoria;
    }

    public void setCmbCategoriaMigratoria(JComboBox<String> cmbCategoriaMigratoria) {
        this.cmbCategoriaMigratoria = cmbCategoriaMigratoria;
    }

    public JLabel getLblErrorCategoriaMigratoria() {
        return lblErrorCategoriaMigratoria;
    }

    public void setLblErrorCategoriaMigratoria(JLabel lblErrorCategoriaMigratoria) {
        this.lblErrorCategoriaMigratoria = lblErrorCategoriaMigratoria;
    }

    public JLabel getLblErrorGenero() {
        return lblErrorGenero;
    }

    public JLabel getLblErrorIdentificacion() {
        return lblErrorIdentificacion;
    }

    public JLabel getLblErrorIdioma() {
        return lblErrorIdioma;
    }

    public JLabel getLblErrorNacionalidad() {
        return lblErrorNacionalidad;
    }

    public JLabel getLblErrorNumeroCasa() {
        return lblErrorNumeroCasa;
    }

    public JLabel getLblErrorParroquiaReside() {
        return lblErrorParroquiaReside;
    }

    public JLabel getLblErrorPorcentaje() {
        return lblErrorPorcentaje;
    }

    public JLabel getLblErrorPriApellido() {
        return lblErrorPriApellido;
    }

    public JLabel getLblErrorPriNombre() {
        return lblErrorPriNombre;
    }

    public JLabel getLblErrorProvincia() {
        return lblErrorProvincia;
    }

    public JLabel getLblErrorProvinciaReside() {
        return lblErrorProvinciaReside;
    }

    public JLabel getLblErrorReferencia() {
        return lblErrorReferencia;
    }

    public JLabel getLblErrorSector() {
        return lblErrorSector;
    }

    public JLabel getLblErrorSegApellido() {
        return lblErrorSegApellido;
    }

    public JLabel getLblErrorSegNombre() {
        return lblErrorSegNombre;
    }

    public JLabel getLblErrorSexo() {
        return lblErrorSexo;
    }

    public JLabel getLblErrorTelefono() {
        return lblErrorTelefono;
    }

    public JLabel getLblErrorTipoDiscapacidad() {
        return lblErrorTipoDiscapacidad;
    }

    public JLabel getLblErrorTipoResidencia() {
        return lblErrorTipoResidencia;
    }

    public JLabel getLblErrorTipoSangre() {
        return lblErrorTipoSangre;
    }

    public JComboBox<String> getCmbPaisReside() {
        return cmbPaisReside;
    }

    public JLabel getLblErrorPaisReside() {
        return lblErrorPaisReside;
    }

    public JComboBox<String> getCmbIdiomas() {
        return cmbIdiomas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbTipoId = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbSexo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cmbEstadoCivil = new javax.swing.JComboBox<>();
        txtSegundoApellido = new javax.swing.JTextField();
        txtPrimerApellido = new javax.swing.JTextField();
        txtPrimerNombre = new javax.swing.JTextField();
        txtSegundoNombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cmbEtnia = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cmbGenero = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cmbTipoSangre = new javax.swing.JComboBox<>();
        lblTipoDiscapacidad = new javax.swing.JLabel();
        cmbTipoDiscapacidad = new javax.swing.JComboBox<>();
        lblPorcentaje = new javax.swing.JLabel();
        txtPorcentaje = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblCarnetConadis = new javax.swing.JLabel();
        txtCarnetConadis = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        cbxDiscapacidad = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        cmbProvincia = new javax.swing.JComboBox<>();
        cmbNacionalidad = new javax.swing.JComboBox<>();
        cmbCanton = new javax.swing.JComboBox<>();
        txtCodigoPostal = new javax.swing.JTextField();
        cmbProvinciaReside = new javax.swing.JComboBox<>();
        cmbCantonReside = new javax.swing.JComboBox<>();
        cmbParroquiaReside = new javax.swing.JComboBox<>();
        txtCallePrincipal = new javax.swing.JTextField();
        txtReferencia = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtNumeroCasa = new javax.swing.JTextField();
        txtSector = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtCalleSecundaria = new javax.swing.JTextField();
        cmbTipoResidencia = new javax.swing.JComboBox<>();
        btnGuardarPersona = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        lblFoto = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        btnBuscarFoto = new javax.swing.JButton();
        btnBuscarPersona = new javax.swing.JButton();
        lblErrorCelular = new javax.swing.JLabel();
        lblErrorIdentificacion = new javax.swing.JLabel();
        lblErrorPorcentaje = new javax.swing.JLabel();
        lblErrorTipoSangre = new javax.swing.JLabel();
        lblErrorPriApellido = new javax.swing.JLabel();
        lblErrorSegNombre = new javax.swing.JLabel();
        lblErrorEtnia = new javax.swing.JLabel();
        lblErrorFecNac = new javax.swing.JLabel();
        lblErrorSexo = new javax.swing.JLabel();
        lblErrorIdioma = new javax.swing.JLabel();
        lblErrorCanton = new javax.swing.JLabel();
        lblErrorCarnetConadis = new javax.swing.JLabel();
        lblErrorGenero = new javax.swing.JLabel();
        lblErrorTipoDiscapacidad = new javax.swing.JLabel();
        lblErrorParroquiaReside = new javax.swing.JLabel();
        lblErrorProvincia = new javax.swing.JLabel();
        lblErrorNacionalidad = new javax.swing.JLabel();
        lblErrorCorreo = new javax.swing.JLabel();
        lblErrorNumeroCasa = new javax.swing.JLabel();
        lblErrorProvinciaReside = new javax.swing.JLabel();
        lblErrorCallePrin = new javax.swing.JLabel();
        lblErrorCalleSec = new javax.swing.JLabel();
        lblErrorCantonReside = new javax.swing.JLabel();
        lblErrorCodigoPostal = new javax.swing.JLabel();
        lblErrorReferencia = new javax.swing.JLabel();
        lblErrorSector = new javax.swing.JLabel();
        lblErrorTipoResidencia = new javax.swing.JLabel();
        lblErrorSegApellido = new javax.swing.JLabel();
        lblErrorTelefono = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        lblErrorEstadoCivil = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        cmbPaisReside = new javax.swing.JComboBox<>();
        lblErrorPaisReside = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cmbIdiomas = new javax.swing.JComboBox<>();
        lblErrorPriNombre = new javax.swing.JLabel();
        btnCapturarFoto = new javax.swing.JButton();
        jdfechaNacimiento = new com.toedter.calendar.JDateChooser();
        cmbCategoriaMigratoria = new javax.swing.JComboBox<>();
        lblErrorCategoriaMigratoria = new javax.swing.JLabel();
        cbxCategoriaMigratoria = new javax.swing.JCheckBox();

        setClosable(true);
        setIconifiable(true);
        setTitle("CREAR NUEVA PERSONA");

        cmbTipoId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "CEDULA", "PASAPORTE" }));

        jLabel2.setText("Identificación *");

        jLabel3.setText("Primer Apellido *");

        jLabel4.setText("Segundo Apellido");

        jLabel5.setText("Fecha Nacimiento *");

        jLabel6.setText("Primer Nombre *");

        jLabel7.setText("Segundo Nombre");

        jLabel8.setText("Sexo *");

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "HOMBRE", "MUJER" }));

        jLabel9.setText("Estado Civíl *");

        cmbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "SOLTERO/A", "CASADO/A", "DIVORCIADO/A", "UNION LIBRE", "VIUDO/A" }));

        jLabel10.setText("Etnia *");

        cmbEtnia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "INDIGENA", "MESTIZO", "MULATO", "AFRO-ECUATORIANO", "BLANCO", "AWA", "ACHUAR", "CHACHI", "COFÁN", "SECOYA", "SHIWIAR", "SHUAR", "TSACHILA", "WAORANI", "ANDOA", "KICHWA DE LA SIERRA", "PASTOS", "OTAVALO", "KARANKI", "KAYAMBI", "CHIBULEOSALASAKA", "KISAPINCHA", "PURUHÁ", "KAÑARI", "SARAGURO", "PALTAS", "HUANCAVILCA", "OTRA ETNIA", "SE IGNORA" }));

        jLabel11.setText("Género *");

        cmbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "MASCULINO", "FEMENINO", "LGBTI" }));

        jLabel12.setText("Tipo Sangre *");

        cmbTipoSangre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "O+", "O-", "A+", "A-", "B+", "B-", "AB+", "AB-" }));

        lblTipoDiscapacidad.setText("Tipo de discapacidad");

        cmbTipoDiscapacidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "AUDITIVA", "FÍSICA", "INTELECTUAL", "MENTAL", "VISUAL", "OTRA" }));

        lblPorcentaje.setText("Porcentaje");

        lblCarnetConadis.setText("Carnet Conadis");

        jLabel17.setText("Seleccione su idioma *");

        cbxDiscapacidad.setText("Discapacidad");
        cbxDiscapacidad.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        cbxDiscapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDiscapacidadActionPerformed(evt);
            }
        });

        jLabel19.setText("Teléfono");

        jLabel20.setText("Celular");

        jLabel21.setText("Correo");

        jLabel23.setText("País Reside *");

        jLabel24.setText("Cantón Reside *");

        jLabel25.setText("Parroquia Reside *");

        jLabel26.setText("Código Postal *");

        jLabel27.setText("Calle Principal *");

        jLabel28.setText("Referencia");

        jLabel29.setText("Nacionalidad *");

        jLabel30.setText("Provincia *");

        jLabel31.setText("Cantón *");

        cmbProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE" }));

        cmbNacionalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "ECUATORIANO/A", "COLOMBIANO/A", "PERUANO/A", "VENEZOLANO/A", " " }));

        cmbCanton.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE" }));

        cmbProvinciaReside.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE" }));

        cmbCantonReside.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE" }));

        cmbParroquiaReside.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE" }));

        jLabel32.setText("Número Casa");

        jLabel33.setText("Sector");

        jLabel34.setText("Calle Secundaria");

        jLabel35.setText("Tipo Residencia *");

        cmbTipoResidencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "ZONA URBANA", "ZONA RURAL" }));

        btnGuardarPersona.setText("Guardar");

        btnCancelar.setText("Cancelar");

        lblFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnBuscarFoto.setText("Buscar Foto");
        btnBuscarFoto.setToolTipText("Buscar una foto en el equipo.");

        btnBuscarPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/icons8_Search_15px.png"))); // NOI18N

        lblErrorCelular.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorCelular.setText("Ingrese un número de celular válido");

        lblErrorIdentificacion.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorIdentificacion.setText("Ingrese 10 dígitos");

        lblErrorPorcentaje.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorPorcentaje.setText("Solo ingrese números");

        lblErrorTipoSangre.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorTipoSangre.setText("Seleccione su tipo de sangre");

        lblErrorPriApellido.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorPriApellido.setText("Sólo debe ingresar letras.");

        lblErrorSegNombre.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorSegNombre.setText("Sólo debe ingresar letras.");

        lblErrorEtnia.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorEtnia.setText("Seleccione su etnia");

        lblErrorFecNac.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorFecNac.setText("Seleccione su fecha de nacimiento");

        lblErrorSexo.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorSexo.setText("Seleccione su sexo");

        lblErrorIdioma.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorIdioma.setText("Seleccione su idioma");

        lblErrorCanton.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorCanton.setText("Seleccione su cantón");

        lblErrorCarnetConadis.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorCarnetConadis.setText("Ingrese un número de carnet válido");

        lblErrorGenero.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorGenero.setText("Seleccione su género");

        lblErrorTipoDiscapacidad.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorTipoDiscapacidad.setText("Seleccione su tipo de discapacidad");

        lblErrorParroquiaReside.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorParroquiaReside.setText("Seleccione su parroquia que reside");

        lblErrorProvincia.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorProvincia.setText("Seleccione su provincia");

        lblErrorNacionalidad.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorNacionalidad.setText("Seleccione su nacionalidad");

        lblErrorCorreo.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorCorreo.setText("Ingrese un correo válido");

        lblErrorNumeroCasa.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorNumeroCasa.setText("Ejémplo: 4-32  ó  s/n");

        lblErrorProvinciaReside.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorProvinciaReside.setText("Seleccione su provincia que reside");

        lblErrorCallePrin.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorCallePrin.setText("Sólo debe ingresar números y letras");

        lblErrorCalleSec.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorCalleSec.setText("Sólo debe ingresar números y letras");

        lblErrorCantonReside.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorCantonReside.setText("Seleccione su cantón que reside");

        lblErrorCodigoPostal.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorCodigoPostal.setText("Sólo debe ingresar números");

        lblErrorReferencia.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorReferencia.setText("Sólo debe ingresar letras.");

        lblErrorSector.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorSector.setText("Sólo debe ingresar letras.");

        lblErrorTipoResidencia.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorTipoResidencia.setText("Seleccione su tipo de residencia");

        lblErrorSegApellido.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorSegApellido.setText("Sólo debe ingresar letras.");

        lblErrorTelefono.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorTelefono.setText("Ingrese un número de teléfono válido");

        lblErrorEstadoCivil.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorEstadoCivil.setText("Seleccione un estado civíl");

        jLabel36.setText("Provincia Reside *");

        cmbPaisReside.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE" }));

        lblErrorPaisReside.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorPaisReside.setText("Seleccione su país de residencia");

        jLabel18.setText("Tipo de Identificación*");

        cmbIdiomas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE" }));

        lblErrorPriNombre.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorPriNombre.setText("Sólo debe ingresar letras.");

        btnCapturarFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/icons8_Webcam_25px.png"))); // NOI18N
        btnCapturarFoto.setToolTipText("Abrir camara.");
        btnCapturarFoto.setBorderPainted(false);
        btnCapturarFoto.setContentAreaFilled(false);
        btnCapturarFoto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/icons8_Web_Camera_25px.png"))); // NOI18N

        cmbCategoriaMigratoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "RESIDENTE PERMANENTE", "RESIDENTE TEMPORAL", "R. TRANSITORIO O NO RESIDENTE", "REFUGIADO" }));

        lblErrorCategoriaMigratoria.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorCategoriaMigratoria.setText("Seleccione su categoria migratoria");

        cbxCategoriaMigratoria.setText("Categoría Migratoria");
        cbxCategoriaMigratoria.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        cbxCategoriaMigratoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoriaMigratoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(cmbTipoId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnBuscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblErrorIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(jLabel9)
                        .addGap(106, 106, 106)
                        .addComponent(cmbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(270, 270, 270)
                        .addComponent(txtSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblErrorPriApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lblErrorSegApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblErrorFecNac, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(227, 227, 227)
                        .addComponent(jLabel19))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(87, 87, 87)
                        .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11)
                        .addGap(86, 86, 86)
                        .addComponent(cmbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel21)
                        .addGap(37, 37, 37)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblErrorSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lblErrorGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(54, 54, 54)
                        .addComponent(cmbTipoSangre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(cmbEtnia, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblErrorTipoSangre, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lblErrorEtnia, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170)
                        .addComponent(lblErrorCategoriaMigratoria))
                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbxDiscapacidad)
                        .addGap(33, 33, 33)
                        .addComponent(lblTipoDiscapacidad)
                        .addGap(41, 41, 41)
                        .addComponent(cmbTipoDiscapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblCarnetConadis)
                        .addGap(36, 36, 36)
                        .addComponent(txtCarnetConadis, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(txtPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblErrorPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrorSegNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblErrorTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(lblErrorIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(30, 30, 30)
                .addComponent(btnBuscarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnCapturarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(540, 540, 540)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblErrorCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(890, 890, 890)
                .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(710, 710, 710)
                .addComponent(cmbIdiomas, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(680, 680, 680)
                .addComponent(lblPorcentaje))
            .addGroup(layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(txtSegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(txtPrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(lblErrorCarnetConadis, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(lblErrorTipoDiscapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 1070, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(540, 540, 540)
                .addComponent(lblErrorCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(540, 540, 540)
                .addComponent(lblErrorEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(txtPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblErrorPriNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jLabel10))
            .addGroup(layout.createSequentialGroup()
                .addGap(860, 860, 860)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(710, 710, 710)
                .addComponent(jdfechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(670, 670, 670)
                .addComponent(cmbCategoriaMigratoria, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(540, 540, 540)
                .addComponent(cbxCategoriaMigratoria))
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 1070, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(cmbNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(460, 460, 460)
                        .addComponent(cmbProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cmbCanton, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblErrorNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblErrorProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(lblErrorCanton, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(cmbPaisReside, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(cmbProvinciaReside, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cmbCantonReside, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblErrorPaisReside, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblErrorProvinciaReside, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(lblErrorCantonReside, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(cmbParroquiaReside, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cmbTipoResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblErrorParroquiaReside, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(lblErrorCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lblErrorTipoResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtCallePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblErrorCallePrin, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lblErrorReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtCalleSecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(txtSector, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtNumeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblErrorCalleSec, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lblErrorSector, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lblErrorNumeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(870, 870, 870)
                .addComponent(btnCancelar)
                .addGap(35, 35, 35)
                .addComponent(btnGuardarPersona))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblErrorSegNombre)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrorPriApellido)
                            .addComponent(lblErrorSegApellido)
                            .addComponent(lblErrorFecNac))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrorTelefono)
                            .addComponent(lblErrorIdioma))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrorSexo)
                            .addComponent(lblErrorGenero))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTipoSangre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbEtnia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrorTipoSangre)
                            .addComponent(lblErrorEtnia)
                            .addComponent(lblErrorCategoriaMigratoria))
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxDiscapacidad)
                            .addComponent(lblTipoDiscapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTipoDiscapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCarnetConadis, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCarnetConadis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(lblErrorPorcentaje))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(btnBuscarFoto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(btnCapturarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(lblErrorCelular))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(cmbIdiomas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(lblPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtSegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtPrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(lblErrorCarnetConadis))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(lblErrorTipoDiscapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(lblErrorCorreo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblErrorEstadoCivil))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(txtPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblErrorPriNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jdfechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(cmbCategoriaMigratoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(cbxCategoriaMigratoria))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCanton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrorNacionalidad)
                    .addComponent(lblErrorProvincia)
                    .addComponent(lblErrorCanton))
                .addGap(6, 6, 6)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPaisReside, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbProvinciaReside, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCantonReside, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrorPaisReside)
                    .addComponent(lblErrorProvinciaReside)
                    .addComponent(lblErrorCantonReside))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbParroquiaReside, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipoResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrorParroquiaReside)
                    .addComponent(lblErrorCodigoPostal)
                    .addComponent(lblErrorTipoResidencia))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCallePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrorCallePrin)
                    .addComponent(lblErrorReferencia))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCalleSecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrorCalleSec)
                    .addComponent(lblErrorSector)
                    .addComponent(lblErrorNumeroCasa))
                .addGap(6, 6, 6)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardarPersona)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxDiscapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDiscapacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDiscapacidadActionPerformed

    private void cbxCategoriaMigratoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoriaMigratoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCategoriaMigratoriaActionPerformed

    public JButton getBtnBuscarPersona() {
        return btnBuscarPersona;
    }

    public void setBtnBuscarPersona(JButton btnBuscarPersona) {
        this.btnBuscarPersona = btnBuscarPersona;
    }

    public JButton getBtnBuscarFoto() {
        return btnBuscarFoto;
    }

    public void setBtnBuscarFoto(JButton btnBuscarFoto) {
        this.btnBuscarFoto = btnBuscarFoto;
    }

    public JButton getBtnCapturarFoto() {
        return btnCapturarFoto;
    }

    public void setBtnCapturarFoto(JButton btnCapturarFoto) {
        this.btnCapturarFoto = btnCapturarFoto;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public JButton getBtnGuardarPersona() {
        return btnGuardarPersona;
    }

    public void setBtnGuardarPersona(JButton btnGuardarPersona) {
        this.btnGuardarPersona = btnGuardarPersona;
    }

    public JCheckBox getCbxDiscapacidad() {
        return cbxDiscapacidad;
    }

    public void setCbxDiscapacidad(JCheckBox cbxDiscapacidad) {
        this.cbxDiscapacidad = cbxDiscapacidad;
    }

    public JComboBox<String> getCmbCanton() {
        return cmbCanton;
    }

    public void setCmbCanton(JComboBox<String> cmbCanton) {
        this.cmbCanton = cmbCanton;
    }

    public JComboBox<String> getCmbCantonReside() {
        return cmbCantonReside;
    }

    public void setCmbCantonReside(JComboBox<String> cmbCantonReside) {
        this.cmbCantonReside = cmbCantonReside;
    }

    public JComboBox<String> getCmbEstadoCivil() {
        return cmbEstadoCivil;
    }

    public void setCmbEstadoCivil(JComboBox<String> cmbEstadoCivil) {
        this.cmbEstadoCivil = cmbEstadoCivil;
    }

    public JComboBox<String> getCmbEtnia() {
        return cmbEtnia;
    }

    public void setCmbEtnia(JComboBox<String> cmbEtnia) {
        this.cmbEtnia = cmbEtnia;
    }

    public JComboBox<String> getCmbGenero() {
        return cmbGenero;
    }

    public void setCmbGenero(JComboBox<String> cmbGenero) {
        this.cmbGenero = cmbGenero;
    }

    public JComboBox<String> getCmbNacionalidad() {
        return cmbNacionalidad;
    }

    public void setCmbNacionalidad(JComboBox<String> cmbNacionalidad) {
        this.cmbNacionalidad = cmbNacionalidad;
    }

    public JComboBox<String> getCmbParroquiaReside() {
        return cmbParroquiaReside;
    }

    public void setCmbParroquiaReside(JComboBox<String> cmbParroquiaReside) {
        this.cmbParroquiaReside = cmbParroquiaReside;
    }

    public JComboBox<String> getCmbProvincia() {
        return cmbProvincia;
    }

    public void setCmbProvincia(JComboBox<String> cmbProvincia) {
        this.cmbProvincia = cmbProvincia;
    }

    public JComboBox<String> getCmbProvinciaReside() {
        return cmbProvinciaReside;
    }

    public void setCmbProvinciaReside(JComboBox<String> cmbProvinciaReside) {
        this.cmbProvinciaReside = cmbProvinciaReside;
    }

    public JComboBox<String> getCmbSexo() {
        return cmbSexo;
    }

    public void setCmbSexo(JComboBox<String> cmbSexo) {
        this.cmbSexo = cmbSexo;
    }

    public JComboBox<String> getCmbTipoDiscapacidad() {
        return cmbTipoDiscapacidad;
    }

    public void setCmbTipoDiscapacidad(JComboBox<String> cmbTipoDiscapacidad) {
        this.cmbTipoDiscapacidad = cmbTipoDiscapacidad;
    }

    public JComboBox<String> getCmbTipoId() {
        return cmbTipoId;
    }

    public void setCmbTipoId(JComboBox<String> cmbTipoId) {
        this.cmbTipoId = cmbTipoId;
    }

    public JComboBox<String> getCmbTipoResidencia() {
        return cmbTipoResidencia;
    }

    public void setCmbTipoResidencia(JComboBox<String> cmbTipoResidencia) {
        this.cmbTipoResidencia = cmbTipoResidencia;
    }

    public JComboBox<String> getCmbTipoSangre() {
        return cmbTipoSangre;
    }

    public void setCmbTipoSangre(JComboBox<String> cmbTipoSangre) {
        this.cmbTipoSangre = cmbTipoSangre;
    }

    public JLabel getojLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public void setjLabel11(JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    public JLabel getjLabel12() {
        return jLabel12;
    }

    public void setjLabel12(JLabel jLabel12) {
        this.jLabel12 = jLabel12;
    }

    public JLabel getLblCarnetConadis() {
        return lblCarnetConadis;
    }

    public void setLblCarnetConadis(JLabel lblCarnetConadis) {
        this.lblCarnetConadis = lblCarnetConadis;
    }

    public JLabel getLblPorcentaje() {
        return lblPorcentaje;
    }

    public void setLblPorcentaje(JLabel lblPorcentaje) {
        this.lblPorcentaje = lblPorcentaje;
    }

    public JLabel getLblTipoDiscapacidad() {
        return lblTipoDiscapacidad;
    }

    public void setLblTipoDiscapacidad(JLabel lblTipoDiscapacidad) {
        this.lblTipoDiscapacidad = lblTipoDiscapacidad;
    }

    public JLabel getjLabel17() {
        return jLabel17;
    }

    public void setjLabel17(JLabel jLabel17) {
        this.jLabel17 = jLabel17;
    }

    public JLabel getjLabel19() {
        return jLabel19;
    }

    public void setjLabel19(JLabel jLabel19) {
        this.jLabel19 = jLabel19;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel20() {
        return jLabel20;
    }

    public void setjLabel20(JLabel jLabel20) {
        this.jLabel20 = jLabel20;
    }

    public JLabel getjLabel21() {
        return jLabel21;
    }

    public void setjLabel21(JLabel jLabel21) {
        this.jLabel21 = jLabel21;
    }

    public JLabel getjLabel22() {
        return lblErrorIdentificacion;
    }

    public void setjLabel22(JLabel jLabel22) {
        this.lblErrorIdentificacion = jLabel22;
    }

    public JLabel getjLabel23() {
        return jLabel23;
    }

    public void setjLabel23(JLabel jLabel23) {
        this.jLabel23 = jLabel23;
    }

    public JLabel getjLabel24() {
        return jLabel24;
    }

    public void setjLabel24(JLabel jLabel24) {
        this.jLabel24 = jLabel24;
    }

    public JLabel getjLabel25() {
        return jLabel25;
    }

    public void setjLabel25(JLabel jLabel25) {
        this.jLabel25 = jLabel25;
    }

    public JLabel getjLabel26() {
        return jLabel26;
    }

    public void setjLabel26(JLabel jLabel26) {
        this.jLabel26 = jLabel26;
    }

    public JLabel getjLabel27() {
        return jLabel27;
    }

    public void setjLabel27(JLabel jLabel27) {
        this.jLabel27 = jLabel27;
    }

    public JLabel getjLabel28() {
        return jLabel28;
    }

    public void setjLabel28(JLabel jLabel28) {
        this.jLabel28 = jLabel28;
    }

    public JLabel getjLabel29() {
        return jLabel29;
    }

    public void setjLabel29(JLabel jLabel29) {
        this.jLabel29 = jLabel29;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel30() {
        return jLabel30;
    }

    public void setjLabel30(JLabel jLabel30) {
        this.jLabel30 = jLabel30;
    }

    public JLabel getjLabel31() {
        return jLabel31;
    }

    public void setjLabel31(JLabel jLabel31) {
        this.jLabel31 = jLabel31;
    }

    public JLabel getjLabel32() {
        return jLabel32;
    }

    public void setjLabel32(JLabel jLabel32) {
        this.jLabel32 = jLabel32;
    }

    public JLabel getjLabel33() {
        return jLabel33;
    }

    public void setjLabel33(JLabel jLabel33) {
        this.jLabel33 = jLabel33;
    }

    public JLabel getjLabel34() {
        return jLabel34;
    }

    public void setjLabel34(JLabel jLabel34) {
        this.jLabel34 = jLabel34;
    }

    public JLabel getjLabel35() {
        return jLabel35;
    }

    public void setjLabel35(JLabel jLabel35) {
        this.jLabel35 = jLabel35;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

//    public DateChooserCombo getJdcFechaNacimiento() {
//        return jdcFechaNacimiento;
//    }
//
//    public void setJdcFechaNacimiento(DateChooserCombo jdcFechaNacimiento) {
//        this.jdcFechaNacimiento = jdcFechaNacimiento;
//    }
    public JLabel getLblFoto() {
        return lblFoto;
    }

    public void setLblFoto(JLabel lblFoto) {
        this.lblFoto = lblFoto;
    }

    public JTextField getTxtCallePrincipal() {
        return txtCallePrincipal;
    }

    public void setTxtCallePrincipal(JTextField txtCallePrincipal) {
        this.txtCallePrincipal = txtCallePrincipal;
    }

    public JTextField getTxtCalleSecundaria() {
        return txtCalleSecundaria;
    }

    public void setTxtCalleSecundaria(JTextField txtCalleSecundaria) {
        this.txtCalleSecundaria = txtCalleSecundaria;
    }

    public JTextField getTxtCarnetConadis() {
        return txtCarnetConadis;
    }

    public void setTxtCarnetConadis(JTextField txtCarnetConadis) {
        this.txtCarnetConadis = txtCarnetConadis;
    }

    public JTextField getTxtCelular() {
        return txtCelular;
    }

    public void setTxtCelular(JTextField txtCelular) {
        this.txtCelular = txtCelular;
    }

    public JTextField getTxtCodigoPostal() {
        return txtCodigoPostal;
    }

    public void setTxtCodigoPostal(JTextField txtCodigoPostal) {
        this.txtCodigoPostal = txtCodigoPostal;
    }

    public JTextField getTxtCorreo() {
        return txtCorreo;
    }

    public void setTxtCorreo(JTextField txtCorreo) {
        this.txtCorreo = txtCorreo;
    }

    public JTextField getTxtIdentificacion() {
        return txtIdentificacion;
    }

    public void setTxtIdentificacion(JTextField txtIdentificacion) {
        this.txtIdentificacion = txtIdentificacion;
    }

    public JTextField getTxtNumeroCasa() {
        return txtNumeroCasa;
    }

    public void setTxtNumeroCasa(JTextField txtNumeroCasa) {
        this.txtNumeroCasa = txtNumeroCasa;
    }

    public JTextField getTxtPorcentaje() {
        return txtPorcentaje;
    }

    public void setTxtPorcentaje(JTextField txtPorcentaje) {
        this.txtPorcentaje = txtPorcentaje;
    }

    public JTextField getTxtPrimerApellido() {
        return txtPrimerApellido;
    }

    public void setTxtPrimerApellido(JTextField txtPrimerApellido) {
        this.txtPrimerApellido = txtPrimerApellido;
    }

    public JTextField getTxtPrimerNombre() {
        return txtPrimerNombre;
    }

    public void setTxtPrimerNombre(JTextField txtPrimerNombre) {
        this.txtPrimerNombre = txtPrimerNombre;
    }

    public JTextField getTxtReferencia() {
        return txtReferencia;
    }

    public void setTxtReferencia(JTextField txtReferencia) {
        this.txtReferencia = txtReferencia;
    }

    public JTextField getTxtSector() {
        return txtSector;
    }

    public void setTxtSector(JTextField txtSector) {
        this.txtSector = txtSector;
    }

    public JTextField getTxtSegundoApellido() {
        return txtSegundoApellido;
    }

    public void setTxtSegundoApellido(JTextField txtSegundoApellido) {
        this.txtSegundoApellido = txtSegundoApellido;
    }

    public JTextField getTxtSegundoNombre() {
        return txtSegundoNombre;
    }

    public void setTxtSegundoNombre(JTextField txtSegundoNombre) {
        this.txtSegundoNombre = txtSegundoNombre;
    }

    public JTextField getTxtTelefono() {
        return txtTelefono;
    }

    public void setTxtTelefono(JTextField txtTelefono) {
        this.txtTelefono = txtTelefono;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarFoto;
    private javax.swing.JButton btnBuscarPersona;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCapturarFoto;
    private javax.swing.JButton btnGuardarPersona;
    private javax.swing.JCheckBox cbxCategoriaMigratoria;
    private javax.swing.JCheckBox cbxDiscapacidad;
    private javax.swing.JComboBox<String> cmbCanton;
    private javax.swing.JComboBox<String> cmbCantonReside;
    private javax.swing.JComboBox<String> cmbCategoriaMigratoria;
    private javax.swing.JComboBox<String> cmbEstadoCivil;
    private javax.swing.JComboBox<String> cmbEtnia;
    private javax.swing.JComboBox<String> cmbGenero;
    private javax.swing.JComboBox<String> cmbIdiomas;
    private javax.swing.JComboBox<String> cmbNacionalidad;
    private javax.swing.JComboBox<String> cmbPaisReside;
    private javax.swing.JComboBox<String> cmbParroquiaReside;
    private javax.swing.JComboBox<String> cmbProvincia;
    private javax.swing.JComboBox<String> cmbProvinciaReside;
    private javax.swing.JComboBox<String> cmbSexo;
    private javax.swing.JComboBox<String> cmbTipoDiscapacidad;
    private javax.swing.JComboBox<String> cmbTipoId;
    private javax.swing.JComboBox<String> cmbTipoResidencia;
    private javax.swing.JComboBox<String> cmbTipoSangre;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private com.toedter.calendar.JDateChooser jdfechaNacimiento;
    private javax.swing.JLabel lblCarnetConadis;
    private javax.swing.JLabel lblErrorCallePrin;
    private javax.swing.JLabel lblErrorCalleSec;
    private javax.swing.JLabel lblErrorCanton;
    private javax.swing.JLabel lblErrorCantonReside;
    private javax.swing.JLabel lblErrorCarnetConadis;
    private javax.swing.JLabel lblErrorCategoriaMigratoria;
    private javax.swing.JLabel lblErrorCelular;
    private javax.swing.JLabel lblErrorCodigoPostal;
    private javax.swing.JLabel lblErrorCorreo;
    private javax.swing.JLabel lblErrorEstadoCivil;
    private javax.swing.JLabel lblErrorEtnia;
    private javax.swing.JLabel lblErrorFecNac;
    private javax.swing.JLabel lblErrorGenero;
    private javax.swing.JLabel lblErrorIdentificacion;
    private javax.swing.JLabel lblErrorIdioma;
    private javax.swing.JLabel lblErrorNacionalidad;
    private javax.swing.JLabel lblErrorNumeroCasa;
    private javax.swing.JLabel lblErrorPaisReside;
    private javax.swing.JLabel lblErrorParroquiaReside;
    private javax.swing.JLabel lblErrorPorcentaje;
    private javax.swing.JLabel lblErrorPriApellido;
    private javax.swing.JLabel lblErrorPriNombre;
    private javax.swing.JLabel lblErrorProvincia;
    private javax.swing.JLabel lblErrorProvinciaReside;
    private javax.swing.JLabel lblErrorReferencia;
    private javax.swing.JLabel lblErrorSector;
    private javax.swing.JLabel lblErrorSegApellido;
    private javax.swing.JLabel lblErrorSegNombre;
    private javax.swing.JLabel lblErrorSexo;
    private javax.swing.JLabel lblErrorTelefono;
    private javax.swing.JLabel lblErrorTipoDiscapacidad;
    private javax.swing.JLabel lblErrorTipoResidencia;
    private javax.swing.JLabel lblErrorTipoSangre;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblPorcentaje;
    private javax.swing.JLabel lblTipoDiscapacidad;
    private javax.swing.JTextField txtCallePrincipal;
    private javax.swing.JTextField txtCalleSecundaria;
    private javax.swing.JTextField txtCarnetConadis;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCodigoPostal;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNumeroCasa;
    private javax.swing.JTextField txtPorcentaje;
    private javax.swing.JTextField txtPrimerApellido;
    private javax.swing.JTextField txtPrimerNombre;
    private javax.swing.JTextField txtReferencia;
    private javax.swing.JTextField txtSector;
    private javax.swing.JTextField txtSegundoApellido;
    private javax.swing.JTextField txtSegundoNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
