package vista.persona;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Johnny
 */
public class VtnAlumno extends javax.swing.JInternalFrame {

    /**
     * Creates new form VtnCarrera
     */
    public VtnAlumno() {
        initComponents();
    }

    public JButton getBtnReporteAlumnos() {
        return btnReporteAlumnos;
    }

    public void setBtnReporteAlumnos(JButton btnReporteAlumnos) {
        this.btnReporteAlumnos = btnReporteAlumnos;
    }

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public JButton getBtnIngresar() {
        return btnIngresar;
    }

    public JLabel getLblResultados() {
        return lblResultados;
    }

    public JButton getBtnEditar() {
        return btnEditar;
    }

    public JTable getTblAlumno() {
        return tblAlumno;
    }

    public JTextField getTxtBuscar() {
        return txtBuscar;
    }

    public JButton getBtn_Materias() {
        return Btn_Materias;
    }

    public void setBtn_Materias(JButton Btn_Materias) {
        this.Btn_Materias = Btn_Materias;
    }


    public JComboBox<String> getCbx_Filtrar() {
        return Cbx_Filtrar;
    }

    public void setCbx_Filtrar(JComboBox<String> Cbx_Filtrar) {
        this.Cbx_Filtrar = Cbx_Filtrar;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlumno = new javax.swing.JTable();
        lblResultados = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnReporteAlumnos = new javax.swing.JButton();
        Btn_Materias = new javax.swing.JButton();
        Cbx_Filtrar = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Alumnos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Buscar:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 17, -1, -1));
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 14, 336, -1));

        btnIngresar.setText("Ingresar");
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 14, 80, -1));

        btnEditar.setText("Editar");
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 14, 80, -1));

        btnEliminar.setText("Eliminar");
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 14, 80, -1));

        tblAlumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Cedula", "Nombre", "Apellido", "Correo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAlumno);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 91, 693, 238));

        lblResultados.setText("0 Resultados obtenidos.");
        getContentPane().add(lblResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 336, 170, -1));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/icons8_Search_15px.png"))); // NOI18N
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 14, 30, -1));

        jLabel2.setText("Reportes:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 340, -1, -1));

        btnReporteAlumnos.setText("Alumnos");
        btnReporteAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteAlumnosActionPerformed(evt);
            }
        });
        getContentPane().add(btnReporteAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 336, -1, -1));

        Btn_Materias.setText("Mostrar Materias Reprobadas");
        getContentPane().add(Btn_Materias, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 336, -1, -1));

        Cbx_Filtrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "|FILTRAR|", "ALUMNOS ELMINADOS", "ALUMNOS RETIRADOS" }));
        getContentPane().add(Cbx_Filtrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 51, -1, -1));

        jLabel3.setText("Filtrar:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 54, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReporteAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteAlumnosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteAlumnosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Materias;
    private javax.swing.JComboBox<String> Cbx_Filtrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnReporteAlumnos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblResultados;
    private javax.swing.JTable tblAlumno;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
