INSERT INTO "SeccionNombreFS" VALUES (1, '1. ESTADO GENERAL DE SALUD');
INSERT INTO "SeccionNombreFS" VALUES (2, '2. DISCAPACIDAD

');
INSERT INTO "SeccionNombreFS" VALUES (3, '3. MEDICAMENTOS

');
INSERT INTO "SeccionNombreFS" VALUES (4, '4. ALERGIAS

');
INSERT INTO "SeccionNombreFS" VALUES (5, '5. TRATAMIENTOS QUIRÚRGICOS

');
INSERT INTO "SeccionNombreFS" VALUES (6, '6. VACUNAS

');
INSERT INTO "SeccionNombreFS" VALUES (7, '7. HISTORIA CLÍNICA FAMILIAR

');
INSERT INTO "SeccionNombreFS" VALUES (8, '8. HÁBITOS

');
INSERT INTO "SeccionNombreFS" VALUES (9, '9. DIETA

');
INSERT INTO "SeccionNombreFS" VALUES (10, '10. ALIMENTACIÓN

');
INSERT INTO "SeccionNombreFS" VALUES (11, '11. ÁREA PSICOLÓGICA

');


