INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (2, 1, 'Si tiene alguna de estas enfermedades por favor marque la/s opciones:', 1, 1);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (23, 19, '¿Ha sido Ud. Sometido a algún tipo de intervención quirúrgica?   SI / NO', 5, 3);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (25, 21, '¿Ha recibido Ud. Algún tipo de vacuna en los últimos 2 años?    SI / NO', 6, 3);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (8, 4, 'Se realiza los controles frecuentes del embarazo SI / NO', 1, 3);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (6, 3, 'Tiempo de embarazo', 1, 4);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (17, 13, 'Indique la calificación obtenida en la prueba ENES', 3, 9);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (19, 15, '¿Qué tipo de alergia padece Ud. Con respecto a los ALIMENTOS? Marque la/s opciones:', 4, 10);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (20, 16, '¿Qué tipo de alergia padece Ud. Con respecto a MEDICAMENTOS? Marque la/s opciones:', 4, 11);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (21, 17, '¿Qué tipo de alergia padece Ud. Con respecto a PICADURAS DE INSECTOS? Marque la/s opciones:', 4, 12);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (22, 18, '¿Qué tipo de alergia padece Ud. Con respecto al MEDIO AMBIENTE? Marque la/s opciones:', 4, 13);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (24, 20, '¿Qué tipo de tratamiento quirúrgico ha recibido Ud.? Marque la/s opciones:', 5, 14);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (26, 22, '¿Qué tipo de vacuna ha recibido Ud? ¿Para qué enfermedad? Marque la/s opciones:', 6, 15);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (28, 24, '¿Qué enfermedad padecen sus padres o hermanos? Marque la/s opciones:', 7, 16);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (31, 27, '¿Cuántos cigarrillos fuma Ud. Al día?', 8, 17);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (34, 30, '¿Con qué frecuencia Ud. Ingiere bebidas alcohólicas?', 8, 19);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (35, 31, '¿Qué tipo de bebidas alcohólicas Ud. Ingiere?', 8, 20);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (38, 34, '¿Con qué frecuencia Ud. Consume drogas?', 8, 19);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (39, 35, '¿Qué tipo de drogas Ud. consume?', 8, 21);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (41, 37, '¿Qué tipo de actividad física Ud. Practica?', 8, 22);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (42, 38, '¿Con qué frecuencia Ud. Practica las actividades físicas?', 8, 23);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (44, 40, '¿Qué tipo de alimentos Ud. Consue con más frecuencia? Marque la/s opciones:', 9, 24);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (45, 41, '¿Cuáles de las siguientes comidas Ud. Ingiere al día? Marque la/s opciones:', 10, 25);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (47, 43, '¿Cuál fue la causa de la asistencia recibida?', 11, 26);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (49, 45, '¿Qué diagnóstico ha recibido?', 11, 27);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (52, 47, '¿Alguien de su familia tiene algún diagnóstico psicológico o psiquiátrico? Describa a continuación:', 11, 28);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (53, 48, 'Mi vida estudiantil es:', 11, 29);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (54, 49, 'Mi situación familiar es: ', 11, 29);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (55, 50, 'Mi situación emocional es:', 11, 29);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (56, 51, 'Mi vida social es:', 11, 29);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (57, 52, 'Cuando tomo una decisión, el resultado es:', 11, 29);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (27, 23, '¿Sus padres o hermanos padecen de alguna enfermedad?   SI / NO', 7, 3);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (29, 25, '¿Ud. Fuma?    SI / NO', 8, 3);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (10, 6, '¿Tiene algún tipo de discapacidad?  SI / NO', 2, 3);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (14, 10, '¿Toma algún medicamento actualmente?   SI / NO', 3, 3);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (18, 14, '¿Padece Ud. De algún tipo de alergia?    SI / NO', 4, 3);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (32, 28, '¿Ud. Ingiere bebidas alcohólicas?     SI / NO', 8, 3);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (36, 32, '¿Ud. Consume drogas?     SI / NO', 8, 3);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (40, 36, '¿Realiza Ud. Algún tipo de actividad física?   SI / NO', 8, 3);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (43, 39, '¿Consume Ud. Una dieta alta en calorías? (Alimentos Grasos como: hamburguesas pizzas, frituras, etc).    SI / NO', 9, 3);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (46, 42, '¿Ha recibido Ud. Asistencia psicológica o psiquiátrica alguna vez en su vida?  SI / NO', 11, 3);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (48, 44, '¿Ha recibido algún diagnóstico psicológico o psiquiátrico alguna vez en su vida?  SI / NO', 11, 3);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (50, 46, '¿Ha recibido medicación como parte del tratamiento?   SI / NO', 11, 3);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (11, 7, 'Número de carnet CONADIS:', 2, 6);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (12, 8, 'Tipo de discapacidad:', 2, 5);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (13, 9, 'Porcentaje de discapacidad:', 2, 7);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (15, 11, 'Por favor escriba el nombre del medicamento que toma.', 3, 5);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (16, 12, 'Fecha en la que rindió la prueba ENES', 3, 8);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (4, 2, 'Actualmente usted o su pareja , ¿Se encuentran en período de gestación? SI / NO', 1, 3);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (9, 5, 'Nombre de la institución pública o privada donde se realiza los controles', 1, 5);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (30, 26, '¿A qué edad inició con el consumo de cigarrillo?', 8, 18);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (33, 29, '¿A qué edad inició con el consumo de bebidas alcohólicas?', 8, 18);
INSERT INTO "Pregunta"("id", "numero", "titulo", "secc_nom_id", "tipo_respuesta_id") VALUES (37, 33, '¿A qué edad inició con el consumo de drogas?', 8, 18);
