INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (1, 'Actualmente usted o su pareja  se encuentran en período de gestación?', 1);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (2, 'Tiempo de embarazo', 2);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (3, 'Se realiza los controles frecuentes del embarazo', 1);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (4, 'Nombre de la institución pública o privada son se realizan los controles', 3);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (5, '¿Tiene algún tipo de discapacidad?', 1);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (6, 'Número de carnet CONADIS:', 3);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (7, 'Tipo de discapacidad:', 3);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (8, 'Porcentaje de discapacidad:', 4);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (9, '¿Toma algún medicamento actualmente?', 1);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (10, 'Escriba el nombre del medicamento que toma', 3);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (11, 'Fecha en la que rindió la prueba ENES', 7);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (12, 'Indique la calificación obtenida en la prueba ENES', 3);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (13, '¿Padece Ud. De algún tipo de alergia?', 1);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (14, '¿Ha sido Ud. Sometido a algún tipo de intervención quirúrgica?', 1);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (15, '¿Ha recibido Ud. Algún tipo de vacuna en los últimos 2 años?', 1);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (16, '¿Sus padres o hermanos padecen de alguna enfermedad?', 1);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (17, '¿Ud. Fuma?', 1);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (18, '¿A qué edad inició con el consumo de cigarrillo?', 8);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (19, '¿Ud. Ingiere bebidas alcohólicas?', 1);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (20, '¿A qué edad inició con el consumo de bebidas alcohólicas?', 8);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (21, '¿Ud. Consume drogas?', 1);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (22, '¿A qué edad inició con el consumo de drogas?', 8);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (23, '¿Realiza Ud. Algún tipo de actividad física?', 1);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (24, '¿Consume Ud. Una dieta alta en calorías? (Alimentos Grasos como: hamburguesas pizzas, frituras, etc).', 1);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (25, '¿Ha recibido Ud. Asistencia psicológica o psiquiátrica alguna vez en su vida?', 1);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (26, '¿Ha recibido algún diagnóstico psicológico o psiquiátrico alguna vez en su vida?', 1);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (27, '¿Alguien de su familia tiene algún diagnóstico psicológico o psiquiátrico?', 3);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (28, 'Mi vida estudiantil es:', 9);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (29, 'Mi situación familiar es:', 9);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (30, 'MI situación emocional es:', 9);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (31, 'Mi vida social es:', 9);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (32, 'Cuando tomo una decisión, el resultado es:', 9);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (33, '¿Ha recibido medicación como parte del tratamiento?', 1);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (34, 'Si tiene alguna de estas enfermedades por favor marque la/s opciones:', 10);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (35, '¿Qué tipo de alergia padece Ud. Con respecto a los ALIMENTOS? Marque la/s opciones:', 10);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (36, '¿Qué tipo de alergia padece Ud. Con respecto a MEDICAMENTOS? Marque la/s opciones:', 10);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (37, '¿Qué tipo de alergia padece Ud. Con respecto a PICADURAS DE INSECTOS? Marque la/s opciones:', 10);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (38, '¿Qué tipo de alergia padece Ud. Con respecto al MEDIO AMBIENTE? Marque la/s opciones:', 10);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (39, '¿Qué tipo de tratamiento quirúrgico ha recibido Ud.? Marque la/s opciones:', 10);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (40, '¿Qué tipo de vacuna ha recibido Ud? ¿Para qué enfermedad? Marque la/s opciones:', 10);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (41, '¿Qué enfermedad padecen sus padres o hermanos? Marque la/s opciones:', 10);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (42, '¿Cuántos cigarrillos fuma Ud. Al día?', 10);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (43, '¿Con qué frecuencia Ud. Ingiere bebidas alcohólicas?', 10);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (44, '¿Qué tipo de bebidas alcohólicas Ud. Ingiere?', 10);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (45, '¿Con qué frecuencia Ud. Consume drogas?', 10);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (46, '¿Qué tipo de drogas Ud. consume?', 10);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (47, '¿Qué tipo de actividad física Ud. Practica?', 10);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (48, '¿Con qué frecuencia Ud. Practica las actividades físicas?', 10);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (49, '¿Qué tipo de alimentos Ud. Consue con más frecuencia? Marque la/s opciones:', 10);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (50, '¿Cuáles de las siguientes comidas Ud. Ingiere al día? Marque la/s opciones:', 10);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (51, '¿Cuál fue la causa de la asistencia recibida?', 10);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (52, '¿Qué diagnóstico ha recibido?', 10);
INSERT INTO "Pregunta"("id", "pregunta", "tipo_respuesta_id") VALUES (53, '¿Recibe Medicación?', 1);
