INSERT INTO "Parametro" VALUES (1, 'Diabetes (Azúcar alto en Sangre)', 1);
INSERT INTO "Parametro" VALUES (2, 'Asma', 1);
INSERT INTO "Parametro" VALUES (3, 'Gastritis', 1);
INSERT INTO "Parametro" VALUES (4, 'Sinusitis Crónica', 1);
INSERT INTO "Parametro" VALUES (5, 'Colon irritable', 1);
INSERT INTO "Parametro" VALUES (6, 'Hipotiroidismo (problemas de Hormona Tiroidea)', 1);
INSERT INTO "Parametro" VALUES (7, 'Rinitis Alérgica', 1);
INSERT INTO "Parametro" VALUES (8, 'Hipertensión Arterial (Presión Alta)', 1);
INSERT INTO "Parametro" VALUES (9, 'Colesterol Alto', 1);
INSERT INTO "Parametro" VALUES (10, 'Esquizofrenia', 1);
INSERT INTO "Parametro" VALUES (11, 'Soya', 10);
INSERT INTO "Parametro" VALUES (12, 'Huevo', 10);
INSERT INTO "Parametro" VALUES (13, 'Camarón', 10);
INSERT INTO "Parametro" VALUES (14, 'Pescado', 10);
INSERT INTO "Parametro" VALUES (15, 'Chocolate', 10);
INSERT INTO "Parametro" VALUES (17, 'Embutidos', 10);
INSERT INTO "Parametro" VALUES (18, 'Leche', 10);
INSERT INTO "Parametro" VALUES (19, 'Nueces', 10);
INSERT INTO "Parametro" VALUES (20, 'Almendras', 10);
INSERT INTO "Parametro" VALUES (21, 'Cítricos', 10);
INSERT INTO "Parametro" VALUES (22, 'Penicilina', 11);
INSERT INTO "Parametro" VALUES (23, 'Amoxicilina', 11);
INSERT INTO "Parametro" VALUES (24, 'Trimetropin Sulfa', 11);
INSERT INTO "Parametro" VALUES (25, 'AINES (Ibuprofeno, Naproxeno, Diclofenaco)', 11);
INSERT INTO "Parametro" VALUES (26, 'Paracetamol', 11);
INSERT INTO "Parametro" VALUES (27, 'Ácido Acetil Salicílico (Aspirina)', 11);
INSERT INTO "Parametro" VALUES (28, 'De abeja', 12);
INSERT INTO "Parametro" VALUES (29, 'De avispa', 12);
INSERT INTO "Parametro" VALUES (30, 'De araña', 12);
INSERT INTO "Parametro" VALUES (31, 'De pulga', 12);
INSERT INTO "Parametro" VALUES (32, 'Polen', 13);
INSERT INTO "Parametro" VALUES (33, 'Polvo', 13);
INSERT INTO "Parametro" VALUES (34, 'Humedad', 13);
INSERT INTO "Parametro" VALUES (35, 'Operación de Apéndice ', 14);
INSERT INTO "Parametro" VALUES (36, 'Operación de la Vesícula por cálculos u otros', 14);
INSERT INTO "Parametro" VALUES (37, 'Operación de la nariz', 14);
INSERT INTO "Parametro" VALUES (38, 'Operación por fracturas', 14);
INSERT INTO "Parametro" VALUES (39, 'Cesárea', 14);
INSERT INTO "Parametro" VALUES (40, 'Hepatitis', 15);
INSERT INTO "Parametro" VALUES (41, 'Influenza', 15);
INSERT INTO "Parametro" VALUES (42, 'Tétanos', 15);
INSERT INTO "Parametro" VALUES (43, 'Obesidad', 16);
INSERT INTO "Parametro" VALUES (44, 'Alergias', 16);
INSERT INTO "Parametro" VALUES (45, 'Cáncer', 16);
INSERT INTO "Parametro" VALUES (46, 'Diabetes', 16);
INSERT INTO "Parametro" VALUES (47, 'Presión Alta', 16);
INSERT INTO "Parametro" VALUES (48, 'Artritis', 16);
INSERT INTO "Parametro" VALUES (51, 'De 1 a 5', 17);
INSERT INTO "Parametro" VALUES (52, 'De 6 a 10', 17);
INSERT INTO "Parametro" VALUES (53, 'De 11 a 15', 17);
INSERT INTO "Parametro" VALUES (54, 'De 16 a 20', 17);
INSERT INTO "Parametro" VALUES (55, 'Diariamente', 19);
INSERT INTO "Parametro" VALUES (56, 'Una vez a la semana', 19);
INSERT INTO "Parametro" VALUES (57, 'Una vez al mes', 19);
INSERT INTO "Parametro" VALUES (58, 'Una vez a los tres meses', 19);
INSERT INTO "Parametro" VALUES (59, 'Una vez a los seis meses', 19);
INSERT INTO "Parametro" VALUES (60, 'Una vez al año', 19);
INSERT INTO "Parametro" VALUES (61, 'Punta', 20);
INSERT INTO "Parametro" VALUES (62, 'Aguardiente', 20);
INSERT INTO "Parametro" VALUES (63, 'Ron', 20);
INSERT INTO "Parametro" VALUES (64, 'Vino', 20);
INSERT INTO "Parametro" VALUES (65, 'Cerveza', 20);
INSERT INTO "Parametro" VALUES (66, 'Cocaína', 21);
INSERT INTO "Parametro" VALUES (67, 'Marihuana', 21);
INSERT INTO "Parametro" VALUES (68, 'Éxtasis', 21);
INSERT INTO "Parametro" VALUES (69, 'Fútbol ', 22);
INSERT INTO "Parametro" VALUES (70, 'Baloncesto', 22);
INSERT INTO "Parametro" VALUES (71, 'Ciclismo', 22);
INSERT INTO "Parametro" VALUES (72, 'Gimnasio', 22);
INSERT INTO "Parametro" VALUES (73, 'Volley ball', 22);
INSERT INTO "Parametro" VALUES (74, 'Natación', 22);
INSERT INTO "Parametro" VALUES (75, 'Tenis', 22);
INSERT INTO "Parametro" VALUES (76, 'Trotar', 22);
INSERT INTO "Parametro" VALUES (77, 'Caminar', 22);
INSERT INTO "Parametro" VALUES (78, 'Danza', 22);
INSERT INTO "Parametro" VALUES (79, 'Deporte de combate (Judo, Taekwondo, Jiu-jitsu, Kick boxing, etc)', 22);
INSERT INTO "Parametro" VALUES (80, '1 día a la semana', 23);
INSERT INTO "Parametro" VALUES (81, '2 días a la semana', 23);
INSERT INTO "Parametro" VALUES (82, '3 días a la semana', 23);
INSERT INTO "Parametro" VALUES (83, '4 días a la semana', 23);
INSERT INTO "Parametro" VALUES (84, '5 días a la semana', 23);
INSERT INTO "Parametro" VALUES (85, '6 días a la semana', 23);
INSERT INTO "Parametro" VALUES (86, '7 días a la semana', 23);
INSERT INTO "Parametro" VALUES (87, 'Chatarra (hamburguesas, papas fritas, etc)', 24);
INSERT INTO "Parametro" VALUES (88, 'Azúcares (refrescos, dulces, helados, etc)', 24);
INSERT INTO "Parametro" VALUES (89, 'Carbohidratos (pan, plátano, yuca, arroz, etc)', 24);
INSERT INTO "Parametro" VALUES (90, 'Frituras', 24);
INSERT INTO "Parametro" VALUES (91, 'Lácteos enteros (leche, yogurt, queso)', 24);
INSERT INTO "Parametro" VALUES (92, 'Grasa animal (carne de res, chancho, etc)', 24);
INSERT INTO "Parametro" VALUES (94, 'Desayuno', 25);
INSERT INTO "Parametro" VALUES (95, 'A media mañana', 25);
INSERT INTO "Parametro" VALUES (96, 'Almuerzo', 25);
INSERT INTO "Parametro" VALUES (97, 'A media tarde', 25);
INSERT INTO "Parametro" VALUES (98, 'Merienda', 25);
INSERT INTO "Parametro" VALUES (99, 'Escolar / académico ', 26);
INSERT INTO "Parametro" VALUES (100, 'Personal', 26);
INSERT INTO "Parametro" VALUES (101, 'Familiar', 26);
INSERT INTO "Parametro" VALUES (102, 'Social', 26);
INSERT INTO "Parametro" VALUES (103, 'Laboral', 26);
INSERT INTO "Parametro" VALUES (104, 'Trastorno del aprendizaje', 27);
INSERT INTO "Parametro" VALUES (105, 'Trastorno por hiperactividad con déficit de atención', 27);
INSERT INTO "Parametro" VALUES (106, 'Depresión', 27);
INSERT INTO "Parametro" VALUES (107, 'Ansiedad', 27);
INSERT INTO "Parametro" VALUES (108, 'Trastorno bipolar', 27);
INSERT INTO "Parametro" VALUES (109, 'Trastornos alimenticios (anorexia, bulimia)', 27);
INSERT INTO "Parametro" VALUES (110, 'Violencia intrafamiliar', 27);
INSERT INTO "Parametro" VALUES (111, 'Consumo de alcohol o drogas', 27);
INSERT INTO "Parametro" VALUES (112, 'Muy Mala', 29);
INSERT INTO "Parametro" VALUES (113, 'Mala', 29);
INSERT INTO "Parametro" VALUES (114, 'Regular', 29);
INSERT INTO "Parametro" VALUES (115, 'Buena', 29);
INSERT INTO "Parametro" VALUES (116, 'Muy Buena', 29);
