/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.prdlectivo;

import datechooser.beans.DateChooserCombo;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JSeparator;
import javax.swing.JTextField;

/**
 *
 * @author Johnny
 */
public class FrmPrdLectivo extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmPrdLectivo
     */
    public FrmPrdLectivo() {
        initComponents();
    }

    public JButton getBtn_Cancelar() {
        return Btn_Cancelar;
    }

    public void setBtn_Cancelar(JButton Btn_Cancelar) {
        this.Btn_Cancelar = Btn_Cancelar;
    }

    public JButton getBtn_Guardar() {
        return Btn_Guardar;
    }

    public void setBtn_Guardar(JButton Btn_Guardar) {
        this.Btn_Guardar = Btn_Guardar;
    }

    public JComboBox<String> getCbx_Carreras() {
        return Cbx_Carreras;
    }

    public void setCbx_Carreras(JComboBox<String> Cbx_Carreras) {
        this.Cbx_Carreras = Cbx_Carreras;
    }

    public DateChooserCombo getDcr_FecConclusion() {
        return Dcr_FecConclusion;
    }

    public void setDcr_FecConclusion(DateChooserCombo Dcr_FecConclusion) {
        this.Dcr_FecConclusion = Dcr_FecConclusion;
    }

    public DateChooserCombo getDcr_FecInicio() {
        return Dcr_FecInicio;
    }

    public void setDcr_FecInicio(DateChooserCombo Dcr_FecInicio) {
        this.Dcr_FecInicio = Dcr_FecInicio;
    }

    public JTextField getTxt_Nombre() {
        return Txt_Nombre;
    }

    public void setTxt_Nombre(JTextField Txt_Nombre) {
        this.Txt_Nombre = Txt_Nombre;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JSeparator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JSeparator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JTextField getTxtObservacion() {
        return txtObservacion;
    }

    public void setTxtObservacion(JTextField txtObservacion) {
        this.txtObservacion = txtObservacion;
    }

    public JLabel getLbl_ErrCarrera() {
        return Lbl_ErrCarrera;
    }

    public void setLbl_ErrCarrera(JLabel Lbl_ErrCarrera) {
        this.Lbl_ErrCarrera = Lbl_ErrCarrera;
    }

    public JLabel getLbl_ErrNombre() {
        return Lbl_ErrNombre;
    }

    public void setLbl_ErrNombre(JLabel Lbl_ErrNombre) {
        this.Lbl_ErrNombre = Lbl_ErrNombre;
    }

    public JLabel getLbl_ErrObservacion() {
        return Lbl_ErrObservacion;
    }

    public void setLbl_ErrObservacion(JLabel Lbl_ErrObservacion) {
        this.Lbl_ErrObservacion = Lbl_ErrObservacion;
    }

    public JLabel getLbl_ErrFecInicio() {
        return Lbl_ErrFecInicio;
    }

    public void setLbl_ErrFecInicio(JLabel Lbl_ErrFecInicio) {
        this.Lbl_ErrFecInicio = Lbl_ErrFecInicio;
    }

    public JLabel getLbl_ErrFecFin() {
        return Lbl_ErrFecFin;
    }

    public void setLbl_ErrFecFin(JLabel Lbl_ErrFecFin) {
        this.Lbl_ErrFecFin = Lbl_ErrFecFin;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtObservacion = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Btn_Guardar = new javax.swing.JButton();
        Btn_Cancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Txt_Nombre = new javax.swing.JTextField();
        Cbx_Carreras = new javax.swing.JComboBox<>();
        Dcr_FecInicio = new datechooser.beans.DateChooserCombo();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Dcr_FecConclusion = new datechooser.beans.DateChooserCombo();
        Lbl_ErrCarrera = new javax.swing.JLabel();
        Lbl_ErrNombre = new javax.swing.JLabel();
        Lbl_ErrObservacion = new javax.swing.JLabel();
        Lbl_ErrFecInicio = new javax.swing.JLabel();
        Lbl_ErrFecFin = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Formulario Periodo Lectivo");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Observación:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 252, -1, -1));
        getContentPane().add(txtObservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 252, 370, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 305, 498, -1));

        Btn_Guardar.setText("Guardar");
        getContentPane().add(Btn_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 320, 104, -1));

        Btn_Cancelar.setText("Cancelar");
        getContentPane().add(Btn_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 320, 104, -1));

        jLabel5.setText("Carrera:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 17, -1, -1));

        jLabel6.setText("Nombre:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 75, -1, -1));
        getContentPane().add(Txt_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 72, 358, -1));

        Cbx_Carreras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "|SELECCIONE|" }));
        getContentPane().add(Cbx_Carreras, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 14, 357, -1));

        try {
            Dcr_FecInicio.setDefaultPeriods(new datechooser.model.multiple.PeriodSet(new datechooser.model.multiple.Period(new java.util.GregorianCalendar(2019, 1, 1),
                new java.util.GregorianCalendar(2019, 1, 1))));
    } catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
        e1.printStackTrace();
    }
    getContentPane().add(Dcr_FecInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 130, 166, -1));

    jLabel1.setText("Fecha de Inicio:");
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 130, -1, -1));

    jLabel2.setText("Fecha de Conclusion:");
    getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

    try {
        Dcr_FecConclusion.setDefaultPeriods(new datechooser.model.multiple.PeriodSet(new datechooser.model.multiple.Period(new java.util.GregorianCalendar(2019, 1, 1),
            new java.util.GregorianCalendar(2019, 1, 1))));
} catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
    e1.printStackTrace();
    }
    getContentPane().add(Dcr_FecConclusion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 166, -1));

    Lbl_ErrCarrera.setForeground(new java.awt.Color(204, 0, 0));
    Lbl_ErrCarrera.setText("Seleccione una Carrera");
    getContentPane().add(Lbl_ErrCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 43, -1, -1));

    Lbl_ErrNombre.setForeground(new java.awt.Color(204, 0, 0));
    Lbl_ErrNombre.setText("Ingrese solo letras");
    getContentPane().add(Lbl_ErrNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

    Lbl_ErrObservacion.setForeground(new java.awt.Color(204, 0, 0));
    Lbl_ErrObservacion.setText("Ingrese una Observacion");
    getContentPane().add(Lbl_ErrObservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 282, -1, -1));

    Lbl_ErrFecInicio.setForeground(new java.awt.Color(204, 0, 0));
    Lbl_ErrFecInicio.setText("Fecha Incorrecta");
    getContentPane().add(Lbl_ErrFecInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

    Lbl_ErrFecFin.setForeground(new java.awt.Color(204, 0, 0));
    Lbl_ErrFecFin.setText("Fecha Incorrecta");
    getContentPane().add(Lbl_ErrFecFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 219, -1, -1));

    pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Cancelar;
    private javax.swing.JButton Btn_Guardar;
    private javax.swing.JComboBox<String> Cbx_Carreras;
    private datechooser.beans.DateChooserCombo Dcr_FecConclusion;
    private datechooser.beans.DateChooserCombo Dcr_FecInicio;
    private javax.swing.JLabel Lbl_ErrCarrera;
    private javax.swing.JLabel Lbl_ErrFecFin;
    private javax.swing.JLabel Lbl_ErrFecInicio;
    private javax.swing.JLabel Lbl_ErrNombre;
    private javax.swing.JLabel Lbl_ErrObservacion;
    private javax.swing.JTextField Txt_Nombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtObservacion;
    // End of variables declaration//GEN-END:variables
}
