
/*
    SI DA ERROR BORRAR ESTA LINEA PORQUE YA DEBE TENER CREADO AL USUARIOS "permisos"
*/
CREATE ROLE "permisos" CREATEROLE LOGIN ENCRYPTED PASSWORD 'ROOT';

    /*
        SOLO EJECUTAR ESTA PARTE PARA DARLE TODOS LOS PERMISOS EN LA BD
    */
    GRANT Delete, Insert, References, Select, Trigger, Truncate, Update ON ALL TABLES IN SCHEMA PUBLIC TO "permisos";
    GRANT Execute ON ALL FUNCTIONS IN SCHEMA PUBLIC TO "permisos";
    GRANT Select, Update, Usage ON ALL SEQUENCES IN SCHEMA PUBLIC TO "permisos";


/*
    SI DA ERROR YA NO EJECUTAR ESTA LINEA!!!!!!
*/
CREATE ROLE "ROOT" SUPERUSER CREATEDB CREATEROLE LOGIN REPLICATION BYPASSRLS PASSWORD 'ROOT';

/*
    SI DA ALGUN 
*/
CREATE ROLE "JOHNNY" CREATEROLE LOGIN PASSWORD 'ROOT';

GRANT "permisos" TO "JOHNNY";



